export const TR = {
    Translator: "Tercüman",
    TranslatorName: "DayiBey32,Türker Akay",
    Language: "Türkçe",
    ThisLanguage: "Türkçe",
    OK: "Tamam",
    SteelMill: "Çelik fabrikası",
    StainlessSteelPlant: "Paslanmaz Çelik Fabrikası",
    CircuitFoundry: "Devre Dökümhanesi",
    IntegratedCircuit: "Entegre Devre",
    OilWell: "Ham Petrol Kuyusu",
    Wood: "Odun",
    LoggingCamp: "Odun Üretimhanesi",
    LumberMill: "Kereste fabrikası",
    Lumber: "Kereste",
    Paper: "Kağıt",
    PaperMill: "Kağıt fabrikası",
    Book: "Kitap",
    BookPublisher: "Kitap yayınlayayıcısı",
    OilRefinery: "Ham Petrol Rafinerisi",
    Sell: "Sat",
    Upgrade: "Yükselt",
    Build: "İnşa et",
    Buildings: "Yapılar",
    Iron: "Demir",
    FuelType: "Yakıt türü seç",
    FuelCost: "Yakıt maliyeti",
    FuelEconomy: "Yakıt ekonomisi",
    FuelInStorage: "%{fuel} Depoda",
    Plastic: "Plastik",
    Petrol: "Benzin",
    Buy: "Sat",
    Multiplier: "Katlayıcı",
    MultiplierDesc: "Her 10 seviyede bir +1 çarpanı alırsınız ",
    SellBuilding: "Yapıyı sat",
    PowerGrid: "Güç ızgarası",
    SortBy: "Göre sırala",
    SortByPrice: "Fiyat",
    SortByAmount: "Miktar",
    NotEnoughResources: "Bu işlem için yeterli kaynak (lar) yok",
    Transportation: "Taşıma",
    Cash: "Para",
    Aluminum: "Alüminyum",
    ResearchPoint: "Araştırma Puanı",
    Unlock: "Araştır",
    BuildingUnlocked: "%{building} ın kilidi açıldı ",
    Science: "Bilim",
    ScienceFromPowerDesc: "Enerji santralleri, güç üretirken az miktarda Bilim üretir",
    Culture: "Kültür",
    School: "Okul",
    University: "Üniverste",
    Polytechnic: "Politeknik",
    Colosseum: "Kolezyum",
    WindTurbine: "Rüzgar türbini",
    Engine: "Motor",
    EngineFactory: "Motor Fabrikası",
    CameraFactory: "Kamera Fabrikası",
    Camera: "Kamera",
    Gun: "Silah",
    GunFactory: "Silah fabrikası",
    Aircraft: "Uçak",
    AircraftFactory: "Uçak fabrikası",
    Zeppelin: "Zeplin",
    ZeppelinFactory: "Zeplin Fabrikası",
    Tank: "Tank",
    TankFactory: "Tank Fabrikası",
    CoalPowerPlant: "Kömür Güç Santrali",
    PetrolPowerPlant: "Petrol Güç Santrali",
    Copper: "Bakır",
    Gas: "Doğalgaz",
    GasPump: "Doğalgaz Pompası",
    GasPowerPlant: "Doğalgaz Güç Santrali",
    Missile: "Füze",
    MissileFactory: "Füze Fabrikası",
    Rocket: "Roket",
    RocketFactory: "Roket Fabrikası",
    BuildingPermit: "Yapı izini",
    BuildingPermitDesc: "%{amount} binalar için izininiz var, ama %{amountBuilt} oluşturdunuz ve %{amountLeft} kaldı",
    BuildingLocked: "Bina henüz mevcut değil, önce araştırma laboratuarında kilidini açmanız gerekir ",
    MaxBuilders: "Maksimum İnşaat",
    MaxBuildersDesc: "Maksimum inşa edebileceğiniz bina sayısı",
    Silicon: "Silikon",
    AluminumMine: "Alimünyum Madeni",
    CopperMine: "Bakır Madeni",
    SiliconMine: "Silikon Madeni",
    IronMine: "Demir Madeni",
    CoalMine: "Kömür madeni",
    Headquarter: "Merkez",
    ResearchLab: "Araştırma Laboratuvarı",
    TradeCenter: "Ticaret Merkezi",
    Resources: "Kaynaklar",
    NotEnoughCash: "Bu işlem için yeterli nakit yok",
    NotEnoughSwissMoney: "Bu operasyon için yeterli Swiss parası yok",
    BuildingNotEnoughFuel: "💡 Yeterli değil %{fuel}",
    AutoSell: "Otomatik Satış",
    Change: "Değiştir",
    StatisticsBureau: "İstatistik Bürosu",
    LogisticsDepartment: "Lojistik Departmanı",
    From: "İtibaren",
    Top20FuelCost: "İlk 20 Yakıt Maliyeti",
    To: "İle",
    TransportTime: "Taşıma Süresi",
    Warehouse: "Depo",
    TradeWarehouse: "Ticaret Deposu",
    Coal: "Kömür",
    Video: "Video",
    ClothingFactory: "Giysi Fabrikası",
    Clothes: "Giysi",
    Fashion: "Moda",
    FashionFactory: "Moda Fabrikası",
    VideoFarm: "Video Çiftliği",
    SantaFactory: "Noel Baba Fabrikası",
    Santa: "Noel Baba",
    Car: "Araba",
    CarFactory: "Araba Fabrikası",
    Ship: "Gemi",
    SolarPanel: "Güneş Paneli",
    SolarPanelDesc: "💡 Güneş Panelleri her 10 saniyede sadece 5 saniye çalışır - tüm döngüler hizalıdır",
    WindTurbineDesc: "💡 Rüzgar Türbinleri her 10 saniyede yalnızca 8 saniye çalışır - döngüler hizalı değildir",
    Movie: "Film",
    MovieStudio: "Film Stüdyosu",
    Sitcom: "Komedi Filmi",
    TVStudio: "TV Stüdyosu",
    PC: "Bilgisayar",
    GameStudio: "Oyun Stüdyosu",
    Game: "Oyun",
    ComputerFactory: "Bilgisayar Fabrikası",
    Shipyard: "Tershane",
    PowerUsage: "Güç Kullanımı",
    PowerSupply: "Güç Kaynağı",
    Level: "Seviye",
    Power: "Güç",
    CentralBank: "Merkez Bankası",
    ResourceInput: "Kaynak Girişi",
    ResourceOutput: "Kaynak Çıkışı",
    ResourceStorage: "Kaynak Deposu",
    ResourceChange: "Kaynak Değişimi",
    ResourceInOutDesc:
        "💡 Karşılık gelen kaynak çıkışı ve kaynak girişi binalarını vurgulamak için yukarıdaki Giriş-Çıkış sayılarına dokunun",
    MarketUpdateIn: "%{time} içinde bir sonraki piyasa fiyatı güncellemesi",
    Semiconductor: "Çip",
    SemiconductorFactory: "Çip Fabrikası",
    Steel: "Çelik",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Bitcoin Çiftliği",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Dogecoin Çiftliği",
    Guitar: "Gitar",
    GuitarFactory: "Gitar Fabrikası",
    Drum: "Davul",
    DrumFactory: "Davul Fabrikası",
    RecordingStudio: "Kayıt Stüdyosu",
    OperaHouse: "Opera binası",
    CoalGasificationPlant: "Kömür Gazlaştırma Tesisi",
    GasProcessingPlant: "Gaz İşleme Tesisi",
    Music: "Müzik",
    Glass: "Cam",
    PhoneFactory: "Telefon Fabrikası",
    Phone: "Telefon",
    GlassFactory: "Cam Fabrikası",
    Oil: "Ham Petrol",
    Chromium: "Krom",
    ChromiumMine: "Krom Madeni",
    Uranium: "Uranyum",
    EnrichedUranium: "Zenginleştirilmiş Uranyum",
    NuclearPowerPlant: "Nükleer Güç Santrali",
    UraniumEnrichmentPlant: "Uranyum Zenginleştirme Tesisi",
    UraniumMine: "Uranyum Madeni",
    Titanium: "Titanyum",
    TitaniumMine: "Titanyum Madeni",
    TitaniumAlloyPlant: "Titanyum Alaşım Tesisi",
    ChromiumAlloyPlant: "Krom Alaşım Tesisi",
    Input: "Girdi",
    PanelPosition: "Panel Pozisyonu",
    Output: "Çıktı",
    OutputCapacity: "Çıktı Kapasitesi",
    ResourceDeposit: "Kaynak Yatırımı",
    AdjacentBonus: "Bitişik Bonusu",
    AdjacentBonusDesc: "Aynı türdeki her bitişik çalışan bina için %{bonus}% ekstra kapasite elde edersiniz",
    ConsiderIncreaseProduction: "💡 %{resource} üretimini artırmayı düşünün",
    ProductionCycleLength: "Üretim Döngüsü",
    ProductionCycleLengthDesc:
        "Saniye cinsinden ölçülen bir üretim döngüsünün süresi. Döngünün uzatılması, döngü başına girdi/çıktıyı buna göre artıracak ve böylece girdi kaynaklarını alırken önceliğini azaltacaktır.",
    MaxInputDistance: "Maksimum Giriş Mesafesi",
    MaxInputDistanceDesc:
        "Bu binanın girdi kaynaklarını alabileceği maksimum mesafe, parça sayısıyla ölçülür",
    AutoSellConcurrency: "Otomatik Satış Eşzamanlılığı",
    AutoSellConcurrencyDesc: "Otomatik satışın aynı anda işleyebileceği maksimum kaynak sayısı",
    MaxAutoSellConcurrencyReached:
        "Maksimum otomatik satış eş zamanlılığına ulaştınız, bunu etkinleştirmek için başka bir otomatik satış özelliğini kapatın",
    WallStreet: "Borsa Merkezi",
    MarketCap: "Piyasa Değeri",
    MarketCapDesc: "Şirketinizin toplam piyasa değeri",
    BuildingValuation: "Bina Değerleme",
    BuildingValuationDesc: "İnşaat izinleri ve iyileştirmeler de dahil olmak üzere binalarınızın toplam değeri",
    ResourcesValuation: "Kaynak Değerlemesi",
    ResourcesValuationDesc: "Envanterinizdeki kaynakların toplam değeri",
    Battery: "Batarya",
    BatteryFactory: "Batarya Fabrikası",
    RatingBuy: "Satın Al",
    RatingSell: "Sat",
    SwissShop: "Swiss Marketi",
    RatingHold: "Tut",
    RatingOutperform: "Daha iyi performans",
    RatingUnderperform: "Düşük performans",
    StockRating: "Fon Değeri",
    JetEngine: "Jet Motoru",
    Helicopter: "Helikopter",
    Lithium: "Lityum",
    LithiumMine: "Lityum Madeni",
    LiionBatteryFactory: "Li-ion Batarya Fabrikası",
    HelicopterFactory: "Helikopter Fabrikası",
    Satellite: "Uydu",
    ToyFactory: "Oyuncak Fabrikası",
    Toy: "Oyuncak",
    SpaceStation: "Uzay İstasyonu",
    SpaceStationFactory: "Uzay İstasyon Fabrikası",
    OperatingSystem: "İşletim Sistemi",
    OperatingSystemCompany: "İşletim Sistem Şirketi",
    LinuxDistribution: "Linux Dağıtımı",
    Internet: "İnternet",
    WebBrowser: "İnternet Tarayıcısı",
    Console: "Konsol",
    ConsoleFactory: "Konsol Fabrikası",
    Train: "Tren",
    TrainFactory: "Tren Fabrikası",
    ShoeFactory: "Ayakkabı Fabrikası",
    Shoes: "Ayakkabı",
    ArtilleryFactory: "Topçu Fabrikası",
    Artillery: "Topçu",
    SubmarineFactory: "Denizaltı Fabrikası",
    Submarine: "Deniz Altı",
    Spaceship: "Uzay Gemisi",
    RobotFactory: "Robot Fabrikası",
    Robot: "Robot",
    SpaceshipFactory: "Uzaygemisi Fabrikası",
    SatelliteFactory: "Uydu Fabrikası",
    JetEngineFactory: "Jet Motor Fabrikası",
    StockRatingDesc:
        "Borsa merkezi analistlerinin piyasa değerinizi etkileyen ve piyasayla birlikte güncellenen hisse senedi derecelendirme konsensüsü",
    OfflineEarning: "Çevrimdışı Kazanç",
    PerMin: "%{amount}/dakika",
    OfflineEarningTime: "Çevrimdışı Kazanç Süresi",
    OfflineEarningTimeDesc: "Bu eşiğe kadar çevrimdışı kazanç elde edeceksiniz",
    BuyPermit: "İzin Satın Al",
    Settings: "Ayarlar",
    Sound: "Ses Efekti",
    SoundDesc: "Tıklama veya hata sesi gibi ses efektini açın",
    MusicDesc: "Muziği Aç: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "Credits",
    Icons: "İkonlar",
    MisplacedBuilding: "⛔ Bu %{building} doğru kaynak deposunun üzerine yerleştirilmedi",
    HighlightBuildings: "Binaları Vurgulayın",
    HighlightTurnedOff: "...bunlar kapalı",
    HighlightStockpileModeOn: "...açık olan stoklama modu",
    HighlightProductionCycleNotDefault: "...üretim döngüsüne sahip olan > 1",
    HighlightMaxInputDistanceNotDefault: "...maksimum giriş mesafesine sahip olan < ∞",
    HighlightNotMakingProfit: "...kar elde etmeyin",
    NBuildingsAreHighlighted: "%{n} building(s) vurgulanıyor",
    TurnOffProduction: "Üretimi Durdur",
    TurnOffProductionDesc:
        "Binanın üretimini kapatın. Bina artık kaynakları taşımayacak ve güç kullanmayacak",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Sınırsız",
    Transport: "Ulaşım",
    TileModifier: "Karo bonusu",
    ShowAllModifiers: "Bütün bonusları gösterin",
    HideAllModifiers: "Tüm Değiştiricileri Gizle",
    NumberOfBuildings: "Bu kadar binan var:",
    ShowContent: "İçerikleri göster",
    HideContent: "içerikleri gizle",
    BuyExpansionPack: "%{price} Kadar fiyat al",
    Cities: "Şehirler",
    InputStrategy: "İçeri Alma Stratejisi",
    InputStrategyClose: "Daha yakın",
    InputStrategyCloseDesc: "Yeterli kaynağa sahip en yakın depoyu tercih edin",
    InputStrategyFar: "Daha uzak",
    InputStrategyFarDesc: "Yeterli kaynağa sahip en uzaktaki depoyu tercih edin",
    InputStrategyAmount: "Miktar",
    InputStrategyAmountDesc: "Mesafeye bakılmaksızın en fazla kaynağın bulunduğu depoyu tercih edin",
    FuelCostSave: "Yakıt Maliyeti Tasarrufu",
    FuelCostSaveDescV2:
        "Depolar, diğer binalara kıyasla kaynakların taşınması için belirli bir oranda yakıt tasarrufu sağlar, seviye ne kadar yüksek olursa tasarruf da o kadar fazla olur",
    SoftwareCompany: "Yazılım Şirketi",
    Software: "Yazılım",
    ScreenFactory: "Ekran Fabrikası",
    Screen: "Ekran",
    JoinDiscord: "En son güncellemeler, ipuçları ve tartışmalar için Discord sunucumuza katılın",
    ClaimOfflineEarning: "Çevrimdışı Ödülünü Topla",
    OfflineTime: "Çevrimdışı zamanı",
    Minutes: "%{time} dakika",
    MaxUpgrade: "Maksimum Yükseltme",
    MaxUpgradeDesc: "Maksimum yükseltmeye ulaştınız",
    ClaimAmount: "Nakit +%{amount}",
    EffectiveTime: "Etkili Zaman",
    EffectiveTimeDesc: "Etkili çevrimdışı kazanç süreniz sınırlıdır %{time}dakika.",
    BuildSearchPlaceholder: "Aranacak binayı veya kaynağı yazın",
    MineOverlayWarning: "%{building} döşeme değiştiriciden etkilenmez",
    WholesaleCenter: "Toptan Satış Merkezi",
    OrderFrom: "Şuradan sipariş ver: %{name}",
    ExpireIn: "Sona Erme Tarihi",
    Reward: "Bedel",
    PerSecond: "%{time}/saniye",
    PolicyPoint: "Politika Puanı",
    PolicyPointDesc: "💡 The more active policies, the more cost for each policy",
    NextOrderIn: "Sıradaki Sipariş",
    FillOrder: "Siparişi gönder",
    RejectOrder: "İptal et",
    WholesaleCenterLocked:
        "Toptan Satış Merkezinin kilidini açmak için en az %{required} farklı kaynağa ihtiyacınız var. Yalnızca %{current} kaynağınız var",
    OrderFilled: "%{from}'dan gelen sipariş başarıyla yerine getirildi!",
    PolicyCenter: "Politika Merkezi",
    NewOrder: "%{from}'dan yeni bir sipariş geldi, lütfen Toptan Satış Merkezi'ni kontrol edin",
    Policies: "Politikalar",
    PolicyNotEnoughTime: "Bu politika için yeterli politika puanınız yok",
    WholesaleCenterOrderFasterDesc: "Toptan Satış Merkezi siparişleri 2 kat daha hızlı alır ve sipariş boyutu 2 kat daha büyük olur",
    PolicyOilWellPowerx2: "Süperşarj ham Petrol Kuyusu",
    PolicyOilWellPowerx2Desc: "Ham Petrol kuyuları 2 kat ham petrol üretir ve 2 kat güç kullanır",
    HalfTransportSpeed: "Tasarruf Etmek İçin Yavaşlayın",
    HalfTransportSpeedDesc: "Taşıma hızı %25 yavaşladı ve yakıt maliyeti %25 azaldı",
    RefineryMoreOil: "Çok Benzin Az Plastik",
    RefineryMoreOilDesc: " Ham Petrol Rafinerileri %50 daha fazla benzin ve %50 daha az plastik üretiyor",
    RefineryMorePlastic: "Çok Plastik Az Benzin",
    RefineryMorePlasticDesc: "Ham Petrol Rafinerileri %50 daha az benzin ve %50 daha fazla plastik üretiyor",
    FreeOilTransportDesc: "Ham Petrol taşımacılığı yakıta mal olmaz ancak ham petrol kuyuları 2 kat güç kullanır",
    SuperSteelMill: "Demir Kalp",
    SuperSteelMillDesc: "Çelik fabrikaları %50 daha az kömür, %25 daha fazla demir ve %25 daha fazla enerji kullanıyor",
    AlSemiconductor: "Alüminyum Devresi",
    AlSemiconductorDesc: "Devre dökümhaneleri bakır yerine alüminyum kullanıyor",
    CostSaver: "Maliyet Tasarrufu",
    CostSaverDesc: "Bir binanın girdi maliyeti çıktısından fazlaysa üretimi durdur",
    CostSaverBuildingDesc:
        "Maliyet Tasarrufu politikası aktif, üretim karlılığa göre otomatik açılıp kapanacak",
    CostSaverBuildingWarning: "Maliyet Tasarrufu politikası etkin, üretimi manuel olarak değiştiremezsiniz",
    GlassUseCoal: "Kara Cam",
    GlassUseCoalDesc: "Cam fabrikaları %50 daha fazla kömür ve %50 daha az silikon kullanıyor",
    AdjacentBonusOnlyOutput: "Bitişik Bonus Plus",
    AdjacentBonusOnlyOutputDesc:
        "Bitişik bonus daha fazla girdi gerektirmez ancak daha fazla güç kullanır ve yalnızca %50 etkilidir",
    IronMine2xOutput: "Yüksek Demir Çıktısı",
    IronMine2xOutputDesc: "Demir madenleri 2 kat daha fazla demir üretir ancak demir taşıma maliyeti 2 kat yakıttır",
    SolarPanelAlwaysWork: "Güneş Asla Batmaz",
    SolarPanelAlwaysWorkDesc: "Güneş paneli zamanın %100'ünde çalışır ancak %60 daha az güç üretir",
    SteelScience: "Çelik Bilgeliği",
    SteelScienceDesc: "Çelik fabrikaları 2 kat ürün girdisi kullanıyor ve ekstra bilim üretiyor",
    ShoppingSpree: "Alışveriş çılgınlığı",
    ShoppingSpreeDesc:
        "Bir kaynağın çıkış kapasitesi yetersiz kalırsa, eksiklik miktarını Ticaret Merkezinden otomatik olarak satın alın (Kaynağın otomatik satışı açıksa bu göz ardı edilecektir)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Alışveriş Çılgınlığı politikası etkin, Ticaret Merkezi, kıtlık halindeki kaynakları otomatik olarak satın alacak",
    ExtraPolicyPoints: "Politiksel Lobici",
    CrAlloyUseFe: "Lityumsuz Krom",
    CrAlloyUseFeDesc: "Krom alaşımlı tesisler Lityum kullanmaz, bunun yerine 2x Demir kullanır",
    DoubleTileModifier: "Doğanın Gücü",
    TileModifierOutputOnly: "Döşeme Değiştirici Plus",
    GasPlantPetrol: "Gaz Sıvılaştırıcı",
    GasPlantPetrolDesc: "Gaz santralleri benzin üretmek için ekstra gaz kullanıyor",
    CoalPlantFuel: "Kömür Sıvılaştırıcı",
    CoalPlantFuelDesc: "Kömür santralleri benzin üretmek için ekstra kömür kullanıyor",
    Welcome: "Hoşgeldin",
    SeeTutorialAgain: "Eğitimi Göster",
    HelpTranslateTheGame: "Dil çevirisine yardımcı ol",
    NextTutorial: "Sıradaki",
    Tutorial1:
        "Industry Idle, fabrikalar inşa ettiğiniz🏭, ürünler ürettiğiniz📦 ve para kazandığınız💸 bir <em>kaynak yönetimi</em> oyunudur.<br><br>Başlamanız için bazı temel kavramların üzerinden geçelim; fazla zamanınızı almaz, serçe parmağımla söz veriyorum.",
    Tutorial2:
        "Tüm binaların elektriğe ihtiyacı vardır⚡, güç üreten bir <em>rüzgar türbininiz</em> vardır. Mevcut güç kaynağınızı üst çubuğun sol tarafında görebilirsiniz.<br><br>Rüzgar türbinlerinin zamanın yalnızca <em>%80</em>'inde çalıştığını fark etmiş olabilirsiniz. Sabit güç üreten diğer türdeki enerji santrallerini inşa etmeyi düşünebilirsiniz.",
    Tutorial3:
        "Haritada çok sayıda <em>kaynak yatırmanız</em> var. Kaynakları çıkarmak için, karşılık gelen depozitonun üzerine⛏️ <em>üzerine</em> mayınlar inşa etmeniz gerekir.<br><br>Örneğin, <em>petrol kuyunuz🛢️</em> var >petrol</em> bir petrol yatağından alınır.<br></br>Kaynak yatakları sınırsızdır; tükenmeleri konusunda endişelenmenize gerek yoktur. Madenlerin dışında herhangi bir boş kiremit üzerine başka binalar da inşa edilebilir.",
    Tutorial5:
        "Para kazanmak için kaynaklarınızı ticaret merkezi aracılığıyla ihraç etmeniz gerekir. Bunu yapmak için söz konusu kaynak için <em>otomatik satışı</em> etkinleştirmeniz yeterlidir.<br></br>Ayrıca ticaret merkezinden de kaynak satın alabilirsiniz. <em>Bir kaynak satın alırsanız fiyatın artacağını</em>, bir kaynak satarsanız fiyatın düşeceğini unutmayın.<br><br>Piyasa <em>değişkendir</em > ve fiyat📈 düzenli olarak değişir.",
    Tutorial6:
        "Yeni binalar inşa etmek için önce <em>araştırma laboratuvarında🧪</em> bu binaların kilidini açmanız gerekir. Araştırma laboratuvarı aynı zamanda bilimi araştırma noktalarına dönüştürür.<br><br>Rüzgar türbininiz (ve diğer enerji santralleriniz) çalışırken az miktarda bilim üretir. Daha sonra bilimi geliştirmek için okul🏫 ve diğer özel binaları inşa edebilirsiniz.<br><br>Artık tüm temel bilgileri öğrendiniz, ekonominizi geliştirmeye başlayın! İşte hızlı bir başlangıç yapmanız için bazı <em>nakit💸</em> ve <em>petrol⛽</em>.",
    WelcomePlay: "Oyna",
    WelcomePlayMuted: "Oyna (🔇Müzik olmadan)",
    Chat: "Sohbet",
    RestoreFromBackup: "Yedekten geri yükle",
    RestoreFromBackupFail: "Yedekleme Steam Cloud'dan geri yüklenemedi: Bir yedekleme olduğundan emin misiniz?",
    RestoreFromBackupTitle: "Emin misin?",
    RestoreFromBackupDesc:
        "Yerel kaydınız kaybolmadığı sürece normalde bulut yedeklemesinden geri yükleme yapmanıza gerek yoktur. Bulut yedeklemesi, yerel kaydetmenizden biraz daha eskidir",
    ChangeName: "İsmini Değiştir",
    SaveName: "Kaydet",
    NameValidationRule: "Adınız yalnızca harf ve rakamlardan oluşmalı ve 5-15 karakter arasında olmalıdır",
    NameValidationRuleProfanity: "Adınız küfür içermemelidir",
    ChatMessageRateLimit: "Yalnızca her 10 saniyede bir yeni sohbet mesajı gönderebilirsiniz",
    NameSaved: "İsmin başarıyla değiştirildi",
    NoMessages: "Yeni mesaj yok",
    Leaderboard: "Lider Sıralaması",
    Name: "İsim",
    Tips1: "Hisse senedi derecelendirmelerinin 5 seviyesi vardır: Satın Al, Yüksek Performans,Elde Tutma, Düşük Performans ve Satış",
    Tips2: "Stoklama modunu açmadığınız sürece, üretim için yeterli kaynak varsa binalar kaynak taşımayı durduracaktır.",
    Tips3: "Kaynak taşımacılığı için yakıt maliyeti, mesafeye ve kaynak miktarına göre belirlenir.",
    Tips4: "Binalar yalnızca haritada bulunan miktarın giriş kapasitesini aşması durumunda kaynak taşıyabilir",
    Tips5: "Binalar Ticaret Merkezi'nden bir kaynağı ancak o kaynak için otomatik satış kapatıldığında taşıyacaktır.",
    Tips6: "İlgili giriş kapasitesi bölümünde bir kaynağın yakıt maliyetini görebilirsiniz.",
    Tips7: "Bir kaynağı satın alırsanız fiyatı artırırsınız. Bir kaynağı satarsanız fiyatı düşürürsünüz",
    Tips8: "İstatistik Bürosu'nda her kaynak miktarına ve zaman içindeki değişimine ilişkin grafiği görebilirsiniz.",
    Tips9: "Bir bina için ihtiyaç duyulan araştırma noktaları, girdi kaynaklarının piyasa fiyatına göre belirlenir.",
    Tips10: "Farklı kaynaklar piyasada farklı fiyatlandırılır; her zaman piyasadaki dalgalanmalara hazırlıklı olun",
    Tips11: "Üretiminizi genişletmeden önce daima güç ve yakıt kaynağınızı kontrol etmek iyi bir fikirdir.",
    FPS30: "Daha az batarya tüketimi",
    OfflineModeDesc:
        "Sunucuya bağlanılamıyor: Çevrimdışı kazançlar oluşturulmayacak. Lütfen internet bağlantınızı kontrol edin",
    OptOut: "Vazgeçmek",
    OptIn: "Sıfırla ve Etkinleştir",
    LeaderboardOptOut: "Skor Tablosundan Ayrılma",
    LeaderboardOptIn: "Skor Tablosunu Sıfırla ve Etkinleştir",
    LeaderboardOptInDesc: "Skor tablosunu yeniden etkinleştirebilmeniz için verilerinizin SIFIRLANMASI gerekiyor, emin misiniz?",
    RewardAdsFailed: "Ödül videosu tamamlanmadı",
    OfflineEarningDoubleSuccess: "Çevrimdışı kazancınızı ikiye katladınız",
    FPS30Desc:
        "Enerji tasarrufu modunu açtığınızda oyunu 60FPS yerine 30FPS hızında çalıştıracaksınız. Bu pilinizin daha uzun süre dayanmasını sağlayacaktır",
    HighlightAll: 'Vurgulamak "%{type}"',
    HighlightInput: "🔍 Vurgulamak %{type} Giriş",
    HighlightOutput: "🔍 Vurgulamak %{type} Çıkış",
    RunOutIn: "Dışında %{time}",
    SwissBank: "Swiss Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Yeni bir şehirde başlarsanız şunları elde edersiniz: %{money} 💵",
    RestorePurchases: "Satın Alınanları Geri Yükle",
    RestorePurchasesSuccess: "Satın aldıklarınız geri yüklendi",
    RestorePurchasesFailed: "Satın aldıklarınız geri yüklenmedi",
    ExpansionPacks: "Genişletme Paketleri",
    ExpansionPack1: "Genişletme Paketi 1",
    RequireExpansionPack1: "Genişletme Paketi 1",
    RequireExpansionPack1Desc: "Bu yalnızca Genişletme Paketi 1 için geçerlidir",
    RequireAnyExpansionPack: "Genişletme Paketine Özel",
    RequireAnyExpansionPackDesc: "Bu özellik, genişletme paketlerinden en az birine sahip olmanızı gerektirir",
    HideRewardAd: "Reklamları gizle",
    HideRewardAdDesc:
        "Tüm oyun içi reklamlar isteğe bağlı ödüllü reklamlardır. Bu, tüm ödüllü reklam seçeneklerini oyundan gizleyecektir.",
    HideDiscordBanner: "Discord Afişi Gizle",
    HideDiscordBannerDesc: "Merkezdeki Discord'u ve mağaza vitrini afişini gizle",
    HideChat: "Sohbet Mesajını Gizle",
    PurchaseFailed: "Satın alma işlemi tamamlanmadı",
    PurchaseSteamContinue: "Lütfen Steam'deki satın alma işleminizi tamamlayın",
    PurchaseSuccess: "Satın alma işlemi tamamlandı, desteğiniz için teşekkürler 👍🏻",
    PrestigeCurrency: "Swiss Parası 💵",
    RestartDesc: "💡 Sadece yeniden başlatmak mı istiyorsunuz? Yukarıdaki Yeni Bir Şehirde Başla seçeneğine dokunabilir ve bulunduğunuz şehri seçebilirsiniz.",
    PrestigeGoBack: "Geri Dön",
    ProductionMultiplier: "Üretim Çarpanı",
    ProductionMultiplierDesc:
        "Tüm binalarınızın üretim kapasitesinde artış (madenler, fabrikalar, enerji santralleri, bilim ve kültür binaları dahil)",
    FuelCostDiscount: "Yakıt Maliyeti İndirimi",
    FuelCostDiscountDesc: "Kaynakların taşınması sırasında yakıt maliyetinde indirim sağlar",
    BuildingPermitCostDivider: "İnşaat Ruhsatı Maliyet Bölücü",
    BuildingPermitCostDividerDesc: "İnşaat ruhsatı maliyetini bu bölene bölün",
    ExtraAdjacentBonus: "Ekstra Bitişik Bonus",
    ExtraAdjacentBonusDesc: "Aynı türdeki her bitişik çalışan bina için ekstra bonus kapasitesi",
    PrestigeAlertTitle: "Emin misin?",
    PrestigeAlertContent:
        "Şirketiniz tasfiye edilecek. %{amount} Swiss parasını nakde çevirecek ve yeni bir şirket kuracaksınız %{city}",
    PrestigeCurrencyDesc:
        "Bu, Swiss banka hesabınızdaki paradır, yeni bir şehre başladığınızda yanınızda taşıyabilirsiniz.",
    Prestige: "Nakit",
    Cancel: "İptal etmek",
    SaveFileCorrupted: "Bozuk Dosyayı Kaydet",
    LoadGameError: "Oyun Yüklenemedi",
    LoadGameErrorMessage: "Hata mesajı: %{message}",
    LoadGameErrorDesc: "Lütfen internet bağlantınızı kontrol edin. Sorun devam ederse lütfen desteğe başvurun",
    ExpansionPackIncompatible:
        "Genişletme paketlerini içeren bir kaydı içe aktarıyorsunuz ancak oyununuzda gerekli genişletme paketleri yok",
    CashIn: "Nakit",
    CurrentCity: "Şu anki şehir",
    CashInDesc:
        "Yeni bir şehirde başlarsanız bu tutarı Swiss banka hesabınıza aktaracaksınız. Bu, şirketinizin piyasa değerine bağlıdır ve kazanabilmeniz için %{amount} değerine ulaşması gerekir Swiss Parası",
    CitySize: "Harita Genişliği",
    GridType: "Klavuz Çizgileri",
    StartInThisCity: "Şehirde Başla %{city}",
    CityBonus: "Şehir Bonusu",
    ResourceTilePercentage: "Kaynaklar",
    MapSquareGrid: "Büyüklük",
    MapHexGrid: "Altıgen",
    Stockholm: "Stockholm",
    Rotterdam: "Rotterdam",
    Oslo: "Oslo",
    StPetersburg: "St. Petersburg",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Zeplin fabrikalarının kilidi açıldı</li><li>Çip fabrikaları 2 kat üretkenliğe sahiptir</li><li>Tersaneler 2 kat kapasiteye sahip</li><li>Araba fabrikaları 2 kat kapasiteye sahip</li><li>Li-ion pil fabrikalarının kilidi açıldı</li>",
    Toulouse: "Toulouse",
    Rome: "Roma",
    RomeBonus:
        "<li>Kolezyumların kilidi açıldı</li><li>Kolezyumlar 2 kat üretkenliğe sahiptir</li><li>5. düzey politika merkeziyle başlayın</li><li>Opera binaları 2 kat kapasiteye sahip</li><li>Kayıt stüdyoları aynı zamanda kültür de üretiyor</li>",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li>5. seviye araştırma laboratuvarıyla başlayın</li><li>Politekniklerin kilidi açıldı</li><li>Politeknikler 2 kat kapasiteye sahiptir</li><li>Okullar 2 kat kapasiteye sahip</li><li>Üniversitenin üretkenliği 2 kat artıyor</li>",
    HideNotProducing: "Üretilmeyen kaynakları gizle",
    SortByStorage: "Depo",
    SortByName: "İsim",
    PlayerTrade: "Oyuncu Ticareti",
    AddTradeFail: "Ticaretiniz eklenemedi",
    AddTradeExceedMaximumTrade:
        "Maksimum %{number} aktif işleminiz olabilir, lütfen önce bunlardan birini talep edin veya iptal edin",
    AddTradeSuccess: "İşleminiz başarıyla eklendi",
    ClaimTradeFail: "Bu takas talep edilemedi, lütfen daha sonra tekrar deneyin",
    CancelTradeSuccess: "İşleminiz başarıyla iptal edildi",
    CancelTradeFail: "Bu takas iptal edilemedi, lütfen daha sonra tekrar deneyin",
    AcceptTradeFail: "Bu takas kabul edilemedi, lütfen daha sonra tekrar deneyin",
    PlayerTradeBanner: "Diğer Oyuncularla Kaynak Ticareti Yapın",
    PlayerTradeResource: "Kaynak",
    PlayerTradeAmount: "Miktar",
    PlayerTradePrice: "Fiyat $",
    PlayerTradeValue: "Değer $",
    PlayerTradeWaiting: "Beklemek...",
    AddTrade: "Ticaret Ekle",
    AcceptTrade: "Kabul etmek",
    CancelTrade: "İptal etmek",
    ClaimTrade: "Almak",
    FailedToImportSave: "Kaydetme İçe Aktarılamadı",
    CancelActiveTradeFirst: "Aktif oyuncu takaslarınız var, lütfen önce bunları iptal edin/talep edin",
    PlayerTradeValidRange: "Menzil: %{min} ~ %{max}",
    PlayerTradeUnavailable:
        "Oyuncularla ticaret yapabilmeniz için üretimde ve depoda en az bir kaynağa sahip olmanız gerekir.",
    PlayerTradeToClaim: "Oyuncu Ticaretinde talep edebileceğiniz %{num} yeni takasınız var",
    PowerBank: "Güç Bankası",
    PowerBankBuildDesc: "Fazla gücü depolayın ve kesinti sırasında güç kaynağı sağlayın",
    WarehouseBuildDesc: "Depolar her türlü kaynağı taşıyabilir ve saklayabilir",
    PowerBankChargeSpeed: "Şarj hızı",
    PowerBankPowerLeft: "Batarya Gücü Kaldı",
    PowerBankMoreCapacity: "Batarya koruyucu",
    PowerBankMoreCapacityDesc: "Güç bankaları %50 hızda şarj olur ancak %50 daha fazla kapasiteye sahiptir",
    PowerBankNotWorking: "⛔ Güç bankaları yalnızca bir elektrik santralinin yanında çalışır",
    ColorTheme: "Renk teması",
    ColorThemeDesc: "Oyun simgeleri, vurgulama, ızgara ve arka plan için renk teması. YENİDEN YÜKLEME GEREKTİRİR",
    SiliconMine2xOutput: "Silikon Vadisi",
    SiliconMine2xOutputDesc:
        "Silikon madenleri 2 kat silikon üretir ancak %50 daha fazla güç kullanır ve silikon taşıma maliyeti %50 daha fazla yakıttır",
    CoalMine2xOutput: "Sanayi devrimi",
    CoalMine2xOutputDesc: "Kömür madenleri 2 kat kömür üretir ancak %50 daha fazla güç kullanır ve kömür taşıma maliyeti %50 daha fazla yakıttır",
    AlMine2xOutput: "Alüminyum Eritme",
    AlMine2xOutputDesc: "Alüminyum madenleri 2 kat alüminyum üretir ve 2 kat daha fazla güç kullanır",
    LoggingCamp2xOutput: "Ormansızlaşma",
    LoggingCamp2xOutputDesc: "Tomruk kampları 2 kat odun üretir ve odun taşıma maliyeti 2 kat yakıttır",
    PowerBankLeft: "Güç Bankası",
    ColorThemeEditor: "Renk Teması Düzenleyicisi",
    ColorThemeEditorDesc: "Geçerli renk temasındaki renkleri geçersiz kılabilirsiniz. Şu anda %{num} geçersiz kılmanız var",
    ColorThemeEditorSave: "Kaydet",
    ColorThemeEditorReset: "Sıfırla",
    ColorThemeEditorResetAll: "Hepsini Sıfırla",
    NewMessageMentions: "Yeni bir mesaj sizden bahsediyor: %{message}",
    HideChatMentions: "Sohbet Bahsetmelerini Gizle",
    HideChatMentionsDesc: "Bir sohbet mesajında benden bahsedildiğinde sesi ve sohbet bildirimini gizleyin,",
    AcceptTradeFailRateLimit: "Her %{time} saniyede yalnızca bir işlemi kabul edebilirsiniz",
    DowngradeBuilding: "Seviye düşürme",
    WarehouseAddInput: "Rota Ekle",
    WarehouseTapToSelect: "Seçmek için Haritaya dokunun...",
    WarehouseFindOnMap: "🔍 Haritada Bul",
    WarehouseRemoveRoute: "Kaldır",
    WarehouseAddRouteFail: "Rota eklenemedi: seçilen döşeme geçerli kaynak değil",
    LevelN: "Seviye %{level}",
    Surplus: "Fazlalık",
    Production: "Üretme",
    Consumption: "Tüketim",
    WarehouseInputCapacityDescV2: "Tüm rotalar arasında eşit olarak bölünmüş toplam iç taşıma kapasitesi",
    PlayerCountryFlag: "Oyuncu bayrağı",
    PlayerCountryChooseFlag: "Ülke Kodunun Alfabetik Sırasıyla",
    WindTurbineAlwaysWork: "Rüzgar yükseliyor",
    WindTurbineAlwaysWorkDesc: "Rüzgar türbinleri zamanın %100'ünde çalışır ancak %30 daha az güç üretir",
    BookPublisherScience: "Bilim Edebiyat",
    BookPublisherScienceDesc: "Kitap yayıncıları kültür yerine bilim üretiyor",
    BatteryFuelEconomy: "Şarj edilebilir batarya",
    BatteryFuelEconomyDesc: "Batarya yakıt ekonomisi %100 oranında artar (yani %50 yakıt maliyeti)",
    ShowTheoreticalInputOutputCapacity: "Teorik giriş/çıkış kapasitesini göster",
    SpecialTransportCost: "Özel Taşıma Maliyetli Kaynaklar",
    FreeTransportCost: "Ücretsiz Taşıma Maliyeti Olan Kaynaklar",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Kaynaklar kümeler halinde ortaya çıkma eğilimindedir</li><li>Depo %50 daha fazla yakıt tasarrufu sağlar</li><li>Benzersiz bina: Manga yayıncısı</li><li>Benzersiz bina: Anime stüdyosu</li><li>Çip fabrikaları 2 kat üretkenliğe sahiptir</li><li>Li-ion batarya fabrikaları 2 kat kapasiteye sahiptir</li><li>Batarya fabrikalarının kilidi açıldı</li><li>Batarya fabrikaları 2 kat kapasiteye sahip</li><li>Batarya yakıt ekonomisi %100 oranında iyileşiyor</li><li>Batarya fabrikaları kömüre ihtiyaç duymuyor</li><li>100K Batarya ile başlayın</li>",
    HideChatDescV2: "Alt araç çubuğundaki sohbet mesajını gizleyin. Sohbet mesajlarını göstererek şunları kabul etmiş olursunuz: ",
    HideChatDescV2ToS: "Kullanım Şartları",
    IntegratedCircuitFab: "Entegre Devre Fabrikası",
    MangaPublisher: "Manga Yayıncısı",
    Manga: "Manga",
    AnimeStudio: "Anime Stüdyosu",
    Anime: "Anime",
    PlayerTradeAction: "Aksiyon",
    PlayerTradeBuy: "Satın Al",
    PlayerTradeSell: "Sat",
    PlayerTradeBid: "Teklif Et",
    PlayerTradeAsk: "Sormak",
    ClaimTradeSuccessV2: "İşleminiz başarıyla talep edildi: %{cashOrResource}",
    AcceptTradeSuccessV2: "Bu takas sizin tarafınızdan kabul edildi: %{cashOrResource}",
    ResourceExplorer: "Kaynak Kaşifi",
    ResourceExplorerDesc: "Boş bir harita döşemesinden kaynak çıkarmanıza olanak tanır",
    ResourceExplorerDescLong: "💡 Kaynak Kaşiflerinin bitişik bonusları yoktur. Güç kullanımı kaynağa göre farklılık gösterir",
    ProductionSettings: "Üretim Ayarları",
    PlayerTradePartialFillTitle: "Doldurma Yüzdesini Seçin",
    PlayerTradeAmountNotValidV2: "İzin verilen minimum işlem tutarı 1'dir",
    PlayerTradeOptOut: "Liderlik tablosundan çıktınız, diğer oyuncularla ticaret yapamazsınız",
    FirstTimeReadGuide: "💡 Nasıl oynanacağı konusunda biraz yardıma mı ihtiyacınız var? Başlangıç kılavuzunu okumak için dokunun!",
    ReadSteamGuideV2: "Oyun Kılavuzları",
    ReadSteamGuideV2Desc: "Topluluk tarafından oluşturulan kılavuzları Steam'de okuyabilir ve kendinizinkini de oluşturabilirsiniz.",
    ChatMessageTooLong: "Sohbet mesajınız izin verilen maksimum karakter sayısını aştı",
    ChatPlaceholderV2: "Mesajını yaz: max %{length} chars",
    ProfitBreakdownOutput: "%{res} Çıkış",
    ProfitBreakdownInput: "%{res} Giriş",
    ProfitBreakdownFuel: "Yakıt maliyeti",
    BuildingProfit: "Kâr",
    RestoreBackup: "Eski haline getirmek",
    SteamLogin: "Steam Üzerinden Giriş Yapın",
    SteamLoginDialogDesc:
        "Yerel kaydınızda Genişletme Paketi etkin, devam etmek için Steam üzerinden oturum açmanız gerekiyor. Veya YEREL KAYDINIZI SİLİP baştan başlayabilirsiniz.",
    SteamLoginDesc: "Steam'de genişletme paketleriniz varsa oturum açtıktan sonra web üzerinde genişletme paketleriyle oynayabilirsiniz",
    SteamLoginYes: "Kayıt olmak",
    SteamLoginNo: "Sil ve Yeniden Başla",
    KungFuDojo: "Kung-Fu Dojo",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Tai-Chi Dojo",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "Uluslar arası İhracat Ticareti",
    FreeTransportToTradeCenterDesc:
        "Ticaret merkezine ulaşım yakıt gerektirmez ancak ticaret merkezinden ulaşım %50 daha fazla yakıta mal olur",
    TaiChi10xCulture: "Doğu'nun incisi",
    PlayerTradeYouHave: "Depoda: %{amount}",
    FiberFactory: "Fiber Fabrikası",
    Fiber: "Fiber",
    Achievements: "Başarılar",
    AchievementsDesc: "%{total} başarıdan %{number} tanesini elde ettiniz",
    AchievementsReward: "Ödül: Swiss Parası +%{swiss}",
    AchievementsRewardToast: "Ödülü talep ettiniz:  Swiss Parası +%{swiss}",
    AchievementsClaim: "Topla",
    AchievementsToast: "%{name}'i başardınız, ödülünüzü Genel Merkezden alın",
    AchievementStockholm100: "Birinci Sınıf Viking",
    AchievementStockholm100Desc: "Tek seferde Stockholm'de 100 Swiss Parası kazanın",
    AchievementStockholm500: "Lisansüstü Viking",
    AchievementStockholm500Desc: "Tek seferde Stockholm'de 500 Swiss Parası kazanın"",
    AchievementStockholm1000: "Deneyimli Viking",
    AchievementStockholm1000Desc: "Tek seferde Stockholm'de 1000 Swiss Parası kazanın",
    AchievementOslo100: "Norveçli Petrol Hobisi",
    AchievementOslo100Desc: "Tek seferde Oslo'da 100 Swiss Parası kazanın",
    AchievementOslo500: "Norveç Petrol Meraklısı",
    AchievementOslo500Desc: "Tek seferde Oslo'da 500 Swiss Parası kazanın",
    AchievementOslo1000: "Norveç Petrol Kralı",
    AchievementOslo1000Desc: "Tek seferde Oslo'da 1000 Swiss Parası kazanın",
    AchievementRotterdam100: "Fırıldak Sahibi",
    AchievementRotterdam100Desc: "Tek seferde Rotterdam'da 100 Swiss Parası kazanın",
    AchievementRotterdam500: "Rüzgar Değirmeni Sahibi",
    AchievementRotterdam500Desc: "Tek seferde Rotterdam'da 500 Swiss Parası kazanın",
    AchievementRotterdam1000: "Rüzgar Türbini Sahibi",
    AchievementRotterdam1000Desc: "Tek seferde Rotterdam'da 1000 Swiss Parası kazanın",
    AchievementDetroit100: "Yerel Araba Satıcısı",
    AchievementDetroit100Desc: "Tek seferde Detroit'te 100 Swiss Parası kazanın",
    AchievementDetroit500: "Bölgesel Araç Distribütörü",
    AchievementDetroit500Desc: "Tek seferde Detroit'te 500 Swiss Parası kazanın",
    AchievementDetroit1000: "Milli Otomobil Tekeli",
    AchievementDetroit1000Desc: "Tek seferde Detroit'te 1000 Swiss Parası kazanın",
    AchievementBoston100: "Para Kazanma Lisansı",
    AchievementBoston100Desc: "Tek seferde Boston'da 100 Swiss Parası kazanın",
    AchievementBoston500: "Para Kazanma Ustası",
    AchievementBoston500Desc: "Tek seferde Boston'da 500 Swiss Parası kazanın",
    AchievementBoston1000: "Para Basma Doktora Programı",
    AchievementBoston1000Desc: "Tek seferde Boston'da 1000 Swiss Parası kazanın",
    AchievementRome100: "Diktatör",
    AchievementRome100Desc: "Tek seferde Roma'da 100 Swiss Parası kazanın",
    AchievementRome500: "Büyük Konstantin",
    AchievementRome500Desc: "Tek seferde Roma'da 500 Swiss Parası kazanın",
    AchievementRome1000: "Sezar Augustus",
    AchievementRome1000Desc: "Tek seferde Roma'da 1000 Swiss Parası kazanın",
    AchievementHamburg100: "Almanya",
    AchievementHamburg100Desc: "Tek seferde Hamburg'da 100 Swiss Parası kazanın",
    AchievementHamburg500: "Anavatan",
    AchievementHamburg500Desc: "Tek seferde Hamburg'da 500 Swiss Parası kazanın",
    AchievementHamburg1000: "Graf Zeplin",
    AchievementHamburg1000Desc: "Tek seferde Hamburg'da 1000 Swiss Parası kazanın",
    AchievementToulouse100: "Jet Uçağı A310",
    AchievementToulouse100Desc: "Tek seferde Toulouse'de 100 Swiss Parası kazanın",
    AchievementToulouse500: "Jet Uçağı A330",
    AchievementToulouse500Desc: "Tek seferde Toulouse'de 500 Swiss Parası kazanın",
    AchievementToulouse1000: "Jet Uçağı A380",
    AchievementToulouse1000Desc: "Tek seferde Toulouse'de 1000 Swiss Parası kazanın",
    AchievementHongKong100: "Hobi Tüccarı",
    AchievementHongKong100Desc: "Tek seferde HongKong'da 100 Swiss Parası kazanın",
    AchievementHongKong500: "Professional Broker",
    AchievementHongKong500Desc: "Tek seferde HongKong'da 500 Swiss Parası kazanın",
    AchievementHongKong1000: "Serbest Fon Yöneticisi",
    AchievementHongKong1000Desc: "Tek seferde HongKong'da 1000 Swiss Parası kazanın",
    AchievementStPetersburg100: "Büyük Dük",
    AchievementStPetersburg100Desc: "Tek seferde St.Petersburg'da 100 Swiss Parası kazanın",
    AchievementStPetersburg500: "Soyluluk Ünvanı",
    AchievementStPetersburg500Desc: "Tek seferde St.Petersburg'da 500 Swiss Parası kazanın",
    AchievementStPetersburg1000: "Tüm Rusya'nın Çarı",
    AchievementStPetersburg1000Desc: "Tek seferde St.Petersburg'da 1000 Swiss Parası kazanın",
    AchievementOsaka100: "Baron",
    AchievementOsaka100Desc: "Tek seferde Osaka'da 100 İsviçre Parası kazanın",
    AchievementOsaka500: "Kont",
    AchievementOsaka500Desc: "Tek seferde Osaka'da 500 İsviçre Parası kazanın",
    AchievementOsaka1000: "Dük",
    AchievementOsaka1000Desc: "Tek seferde Osaka'da 1000 İsviçre Parası kazanın",
    SteamAutoCloudBackup: "Steam Cloud Otomatik Yedekleme",
    SteamAutoCloudBackupFailed: "Steam Cloud Otomatik Yedekleme Başarısız Oldu: %{error}",
    SteamManualBackup: "Bulut'a kaydetmeye zorla",
    UILoading: "Yükleniyor...",
    BuildingResourceBreakdown: "Boşta Tutar Dağılımı",
    SortByDeficit: "Açık",
    SortByRunOut: "Sızma",
    SocialNetworkInc: "Sosyal Ağ Şirketi",
    SocialNetwork: "Sosyal ağ",
    DatabaseCompany: "Veritabanı Şirketi",
    Database: "Veritabanı",
    SatelinkInc: "Uydu Şirketi",
    GameStationInc: "Oyun İstasyonu Şirketi",
    AirShuttleInc: "Hava Mekiği Şirketi",
    AircraftCarrierFactory: "Uçak Gemisi Fabrikası",
    AircraftCarrier: "Uçak Gemisi",
    MapExclusive: "Haritaya Özel",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Araba fabrikaları benzin yerine Batarya kullanıyor ve miktarın yalnızca %50'sine ihtiyaç duyuyor",
    HongKongBonusV2:
        "<li>Benzersiz piyasa fiyatlandırma algoritması - fiyatlar ve hisse senedi derecelendirmesi normal dağılımı takip eder (bell curve)</li><li>Piyasa güncellemeleri ve ticaret kotalarının sıfırlanması iki kat daha sık oluyor (Her saat)</li><li>Araştırmanın kilidi takas edilen kaynaklar aracılığıyla açılabilir</li><li>Benzersiz Bina: Kung-Fu Dojo</li><li>Benzersiz Bina: Tai-Chi Dojo</li><li>İzin verilen maksimum aktif oyuncu takası sayısında %50 artış</li><li>Eşzamanlı 1 Otomatik satış ile başlayın</li><li>Benzersiz politika: Uluslararası İhracat Ticareti</li><li>Benzersiz politika: Doğunun İncisi</li><li>Toptan Satış Merkezi'nin kilidini açmak için yalnızca 4 kaynağa ihtiyacı var</li><li>100M Nakit İle Başlayın</li>",
    TaiChi10xCultureDescV2:
        "Ücretsiz Kung-fu ve Tai-chi ulaşımı. Film stüdyoları 2 kat kapasiteye sahiptir ancak %50 daha fazla güç kullanır",
    SettingsFullScreen: "Tam Ekran",
    SettingsFullScreenDesc: "Oyunu tam ekran modunda çalıştırın. Yalnızca Steam sürümü için kullanılabilir",
    LeaderboardByAllPrestigeCurrency: "Tüm Zamanların Kazanılan Swiss Parası",
    LeaderboardByCash: "Mevcut Eldeki Nakit",
    LeaderboardTotalValuation: "Toplam Değerleme",
    LeaderboardDescV2: "En iyi oyuncuların nerede olduğunu görün",
    LastUpdatedAt: "Son Güncelleme Tarihi:",
    DetroitBonusV3:
        "<li>Motor fabrikaları açıldı,</li><li>Motor fabrikaları 2 kat üretkenliğe sahiptir</li><li>Araba fabrikaları 2 kat kapasiteye sahip</li><li>Araba fabrikaları benzin yerine gaz kullanıyor</li><li>Ücretsiz araçla ulaşım</li><li>Nikola Tesla politikası ücretizdir</li><li>Tren fabrikaları 2 kat kapasiteye sahip</li>",
    SaveAndExit: "Kaydet ve Oyundan Çık",
    SaveAndExitDesc:
        "Kaydet ve oyundan çık. Bu yalnızca Steam sürümünde mevcuttur ve pencere çubuğundaki kapatma düğmesiyle aynı işlevi görür",
    AutoSellResourceWarningShortLabel: "💡Otomatik Satış",
    AutoSellResourceWarningDesc:
        "Bu kaynağı otomatik olarak satıyorsunuz, Ticaret Merkezinde depolanan tutar burada kullanılamaz",
    PlayerTradeLocalPrice: "Yerel Fiyat: %{price}",
    ChatForceScroll: "Kaydırmayı Zorla",
    ChatForceScrollDesc:
        "Zorla kaydırma açıksa, yeni bir mesaj geldiğinde sohbet kaydırılır. Aksi takdirde, yalnızca zaten en altta olduğunuzda kayar",
    ResourceExplorer2: "Kaynak Kaşifi 2.0",
    ConstructionCancel: "İptal Et",
    PolicyBlueprint: "Taslak",
    PolicyBlueprintDesc:
        "Bir binanın inşaatı otomatik olarak başlamaz, manuel olarak başlatılması gerekir (BEDAVA POLİTİKA)",
    HighlightUnderConstruction: "...Üretimi Durdurulanlar",
    HighlightUnderLevel10: "... 10. seviyenin altında olanlar",
    HighlightUnderLevel20: "... 20. seviyenin altında olanlar",
    HighlightUnderLevel30: "... 30. seviyenin altında olanlar",
    Logout: "Oturumu Kapattınız",
    ConstructionStatusQueueingV2: "Sıraya girme",
    ConstructionStatusPausedV2: "Duraklatıldı",
    ConstructionStatusBuildingV2: "Bina",
    ConstructionStatusUnpaidV2: "ödenmemiş",
    ConstructionStatus: "İnşaat Durumu",
    ConstructionStart: "Başlangıç",
    CostFree: "Bedeva",
    PlaceBlueprint: "Bir bina planı yerleştirmek ücretsizdir",
    PlayerTradePriceNotValidV2: "İşlem fiyatı %{min} ile %{max} arasında olmalıdır",
    MarketNews: "Piyasa Haberleri",
    MarketNewsApplyToYou: "Sadece sen",
    MarketNewsApplyToGlobal: "Küresel",
    MarketNewsHighlightAffected: "🔍 Vurgulamak",
    MarketNewsFilterInput: "Tüm %{res} girişi ",
    MarketNewsFilterOutput: "Tüm %{res} çıktısı ",
    MarketNewsFilterBoth: "Tüm %{res} giriş ve çıkışı ",
    MarketNewsIncrease: "kadar arttı %{percent}",
    MarketNewsDecrease: "azaldı %{percent}",
    MarketNewsBuilding: "Bu bina %{num} haberden etkilendi",
    StockholmBonusV2:
        "<li>Benzersiz Bina: Müzik Yapımcısı</li><li>Tomruk kamplarında 2 kat çıkış var</li><li>Kağıt fabrikalarının kilidi açıldı</li><li>Devre dökümhaneleri 2 kat üretkenliğe sahiptir</li><li>Bilim Edebiyatı politikası ücretsizdir</li>",
    FreeOilTransportV2: "Elektrikli Ham Petrol Taşımacılığı",
    Tutorial4P1:
        "Kaynak taşımanın yakıt maliyeti vardır. Birkaç yakıt türü var ve şu anda kullanıyorsunuz <em>Benzin⛽</em> yakıt olarak. Senin bir <em>Ham petrol rafinerisi</em> Ham Petrol kuyusundan ham petrolü taşıyan ve benzin üreten.<br><br>Minik hareketli <em>noktalar</em> kaynakların gerçek zamanlı hareketini temsil eder. Seyahat mesafesini en aza indirmek için bina konumlarınızı optimize etmelisiniz.<br><br><em>Yükseltme</em> Binalarınız çıktılarını artıracak, aynı zamanda güç kullanımını ve gerekli girdiyi de artıracaktır.",
    Tutorial4P2:
        "Yakıt türünü şuradan değiştirebilirsiniz:<em>lojistik Departmanı🚦</em> - bu haritada şunları da kullanabilirsiniz: <em>Doğal Gaz</em> yakıt olarak.<br><br>Lojistik departmanı aynı zamanda en çok yakıt tüketen nakliye rotalarınızı da gösterir; buna göz kulak olmak isteyeceksinizdir.<br><br>Hatırla <em>Yakıt üretiminizin tüketimin üzerinde olduğundan emin olun</em> Aksi halde yakıtınız bittiğinde üretiminiz duracaktır.<br><br>Böyle bir durumda endişelenmeyin, ticaret merkezinden veya diğer oyunculardan acil durum yakıtı satın alabilirsiniz.",
    Tutorial5P2:
        "<em>İstatistik bürosu📊</em> Üretiminize iyi bir genel bakış sağlar. Kaynaklarınızın giriş ve çıkışının ayrıntılı bir dökümünü görebilirsiniz.<br><br>Ayrıca birçok yararlı grafik var📈 -Üretiminizi dengelediğinizde bunlara başvurmak isteyeceksiniz.<br></br>Senin <em>nakit💰, güç fazlası⚡ ve yakıt fazlası⛽</em> sayılar da sol üst köşede gösterilir; bunlardan herhangi biri kırmızıya dönerse, neler olduğunu araştırmalısınız.",
    MusicProducer: "Müzik Yapımcısı",
    PlasticFiber: "Plastik İplik",
    PlasticFiberDesc: "İplik fabrikaları %50 daha fazla plastik, %50 daha az cam kullanıyor",
    SellRefundPercentage: "Satış/Seviye Düşürme",
    SellRefundPercentageDesc:
        "Bir binayı satarsanız veya seviyesini düşürürseniz bu, size iade edilen nakit ve kaynakların yüzdesidir",
    SellBuildingDescV2:
        "Bir bina sattığınızda yatırımınızın %{percent} kısmı size geri ödenecek ve kaynakların %{percent} kısmı Ticaret Merkezine taşınacak",
    BuilderMoveSpeed: "İnşaatçı Hareket Hızı",
    BuilderMoveSpeedDesc: "İnşaatçıların bina inşatına gidiş hızı",
    EBookInc: "E-kitap Şirketi",
    ResourceBooster: "Kaynak Güçlendirici",
    BuildWarningTitle: "Bina Çalışmayabilir",
    BuildWarningTitleDesc: "%{reason}. Bu döşemenin üzerine inşa edeceğinizden emin misiniz?",
    BuildWarningBuildAnyway: "Yine de Oluştur",
    ResourceBoosterNotWorking: "⛔ Kaynak güçlendiriciler yalnızca maden yataklarının yanında çalışır",
    ResourceBoosterBuildings: "Binalar Güçlendiriliyor",
    BuildingResourceConversion: "%{resource} Dönüştürmek",
    AllTimeSwissMoneyEarned: "Tüm zamanların kazanılan Swiss Parası: %{number}",
    BuildingUpgradeCostDivider: "Bina Yükseltme Maliyet Bölücü",
    AchievementSoftwareGiant: "Yazılım Devi",
    AchievementSoftwareGiantDesc:
        "Aynı harita üzerinde 10. seviye Yazılım Şirketi, 10. seviye İşletim Sistemi Şirketi, 10. seviye Veritabanı Şirketi ve 10. seviye Web Tarayıcısı oluşturun",
    AchievementSpaceRace: "Uzay yarışı",
    AchievementSpaceRaceDesc:
        "Aynı harita üzerinde 10. seviye Roket Fabrikası, 10. seviye Uydu Fabrikası, 10. seviye Uzay Gemisi Fabrikası ve 10. seviye Uzay İstasyonu Fabrikası inşa edin",
    AchievementToTheMoon: "Ay'a Gidiş",
    AchievementToTheMoonDesc:
        "40. seviye Bitcoin Çiftliği ve 40. seviye Dogecoin Çiftliği inşa edin. 1B Bitcoin ve 1B Dogecoin'e sahip olun",
    ItsAllGreen: "Hepsi Yeşil",
    ItsAllGreenDesc: "50 Üretim hattına sahip olun ve üretim açığınız olmasın",
    DeepInRed: "Kırmızının Derinliği",
    DeepInRedDesc: "Üretim açığı veren 50 üretim hattına sahip olmak",
    UseScientificNotation: "Bilimsel Gösterimi Kullan",
    UseScientificNotationDesc: "999,9T'den büyük sayılar için bilimsel gösterimi (e gösterimi) kullanın",
    LogoutDescV2:
        "Başka bir cihazda oturum açtınız, bu cihazda oturum kapatıldı. Tekrar giriş yapabilirsiniz ancak diğer cihazda çıkış yapılacaktır",
    LogBackIn: "Tekrar Giriş Yapın",
    ServerDisconnected:
        "Sunucuyla bağlantınız kesildi, lütfen internet bağlantınızı kontrol edin ve oyunu yeniden başlatın.",
    BuildingUpgradeCostDividerDescV2: "Bina yükseltme maliyetini bu bölücüye bölün",
    ResourceBoosterDesc: "Bitişik madenlerin çıktısını artırın",
    BlockUserChatTitle: "%{user} Engelle",
    BlockUserChatAction: "Engelle",
    BlockUserChatDesc:
        "Engelleme bu oyun oturumu sırasında geçerli olacaktır ve oyunu yeniden başlatmadığınız sürece bunu geri alamazsınız",
    ChangeNameCooldown: " %{hour} Saat",
    AtomicBombFactory: "Atomik Bomba Fabrikası",
    AtomicBomb: "Atomik Bomba",
    DynamiteFactory: "Dinamit Fabrikası",
    Dynamite: "Dinamit",
    NuclearMissileFactory: "Nükleer Füze Fabrikası",
    NuclearMissile: "Nükleer Füze",
    LiquidPropellantFactory: "Sıvı Sıkıştırcı Fabrikası",
    GasPropellantFactory: "Gaz Sıkıştırıcı Fabrikası",
    Propellant: "İtici gaz",
    ProjectV2: "Proje V-2",
    ICBMFactory: "Kıtalararası Balistik Füze Fabrikası",
    ICBM: "Kıtalararası Balistik Füze",
    RadarFactory: "Radar Fabrikası",
    Radar: "Radar",
    SpaceForceCommand: "Uzay Kuvvetleri Komutanlığı",
    SpaceForce: "Uzay Kuvveti",
    SpaceColony: "Uzay Kolonisi",
    SpaceColonyInc: "Uzay Kolonisi Şirketi",
    ProjectVostok: "Vostok Projesi",
    AdjacentBonusSquare: "Bitişik Bonus Meydanı",
    AdjacentBonusSquareDesc: "Bitişik bonus %50 daha etkilidir, ancak döşeme değiştiricileri -%15'ten +%15'e kadar ölçeklenir",
    ResourceBoosterSquare: "Kaynak Güçlendirici Meydanı",
    ResourceBoosterSquareDesc:
        "Kaynak güçlendiriciler %25 daha fazla destek sağlar ancak bilim girdisi ve güç kullanımı da %25 artar",
    SteelMillx2: "Çelik Fırını Modernizasyonu",
    SteelMillx2Desc: "Çelik fabrikaları ve paslanmaz çelik tesisleri 2 kat kapasiteye sahiptir ancak 2 kat güç kullanır",
    FuelDynamite: "Yakıt Dinamiti",
    FuelDynamiteDesc: "Dinamit fabrikaları benzin yerine mevcut yakıtınızı kullanıyor",
    StPetersburgBonusV2:
        "<li>Uranyum madenleri 2 kat çıktıya sahiptir</li><li>Uranyum zenginleştirme tesisleri 2 kat kapasiteye sahip</li><li>Uranyum taşımanın maliyeti %50 daha az yakıttır</li><li>Ücretsiz silah taşımacılığı</li><li>Vostok Projesi 2 kat kapasiteye sahip</li>",
    ToulouseBonusV2:
        "<li>Titanyum madenleri 2 kat çıktıya sahiptir</li><li>Uranyum zenginleştirme tesisleri 2 kat üretkenliğe sahiptir</li><li>Jet motoru fabrikaları 2 kat kapasiteye sahip</li><li>Uçak fabrikaları 2 kat üretkenliğe sahiptir</li><li>Roket fabrikaları 2 kat kapasiteye sahip</li>",
    BuildingPermitsNeededDesc: "Yeterli inşaat izniniz olmadığı için bu bina inşaat edilemiyor",
    BuildingPermitsNeeded: "İnşaat İzinleri Gerekiyor",
    BuyMissingPermits: "Eksik İzinleri Satın Al",
    GPUIsBusy: "GPU'lar Meşgul",
    GPUIsBusyDesc:
        "GPU başka görevlerle meşgul olduğundan işletim sisteminiz oyunun grafiklerini duraklattı. Devam etmek için oyunu yeniden yükleyebilirsiniz. Eğer işe yaramazsa oyunu yeniden başlatmayı deneyin",
    SaveAndReloadGame: "Oyunu Kaydet ve Yeniden Yükle",
    ResearchLabCultureInput: "Rönesans",
    ResearchLabCultureInputDesc: "Araştırma Laboratuvarı 2 kat kapasiteye sahiptir ancak kültürü ekstra girdi olarak alır",
    GasPumpx2Output: "Yüksek Basınçlı Gaz Pompası",
    GasPumpx2OutputDesc: "Doğalgaz pompaları 2 kat çıkışa sahiptir ancak 2 kat güç kullanırlar",
    LeaderboardValuationPerHour: "Saatlik Toplam Değerleme",
    LeaderboardValuationPerHourPerSwiss: "Swiss Başına Saatlik Toplam Değerleme",
    LeaderboardValuationPerHourNewPlayers: "Saatlik Toplam Değerleme (< 1000 Swiss)",
    LeaderboardValuationPerBuilding: "Bina Başına Bina Değerlemesi",
    BuildingCustomColor: "Yapı Rengi",
    BuildingCustomColorReset: "Sıfırla",
    Vancouver: "Vancouver",
    VancouverBonus:
        "<li>Every 4 farklı bina tipi 1 adet ücretsiz yapı ruhsatı vermektedir.</li><li>Benzersiz politika: Üretim Çeşitlendirmesi</li><li>Benzersiz Bina: Akçaağaç Şurubu Fabrikası</li><li>Bedava Akçaağaç şurubu taşıma</li><li>Benzersiz yakıt türü: Akçaağaç Şurubu</li><li>Uranyum ve Zenginleştirilmiş Uranyum ticareti yaparken 2 kat oyuncu ticaret kotası</li><li>Özel BEDAVA POLİTİKA: Şurup Plastik</li><li>Oyuncak fabrikaları 2x kadar fazla üretir</li><li>Oyun stüdyoları 2 kat kapasiteye sahiptir</li>",
    MapExtraPermitDesc: " %{number} kadar bedeva yapı izni aldın,haritanın's özel bonusu nedeniyle",
    OsloBonusV3:
        "<li>Ham Petrol rafinerilerinin kilidi açıldı</li><li>Ham Petrol rafinerileri 2 kat kapasiteye sahip</li><li>Elektrikli Ham Petrol taşıma politikası ücretsizdir</li><li>Gaz işleme tesisleri 2 kat kapasiteye sahiptir</li><li>Bedava seviye 4 rüzgar türbini x1</li><li>Bedava seviye 8 ham petrol kuyusu x1</li><li>Bedava seviye 2 ham petrol rafinesi x1</li><li>Bedava seviye 2 doğal gaz pompası x1</li>",
    ResourceBoosterPercentageV2: "💡 Bu tutar şunları içerir: %{percent} bitişik kaynak güçlendiricilerden destek",
    MapleSyrup: "Akçaağaç şurubu",
    MapleSyrupFactory: "Akçaağaç Şurubu Fabrikası",
    SyrupPlastic: "Plastik Yerine Şurup",
    SyrupPlasticDesc: "Plastik kullanan tüm binalar bunun yerine akçaağaç şurubu kullanıyor",
    ResourceBoosterSupplyChain: "Tedarik Zinciri Güçlendirici",
    ResourceBoosterSupplyChainDesc:
        "Kaynak güçlendiriciler 2 kat güç ve bilim kullanır, ancak çalışan her maden için bir kaynak güçlendirici güçlendirir, aynı zamanda madenin çıktısını tüketen komşu fabrikalara da kapasite artışı sağlar (fabrika sadece mevduat tüketmeli)",
    ProductionDiversification: "Üretim Çeşitlendirmesi",
    ProductionDiversificationDesc: "Her farklı bina türü, tüm binalara %1 ekstra kapasite sağlar",
    ExtraPolicyPointsDescV2: "Politika merkezi 2 kat politika puanı dönüştürme kapasitesine sahiptir",
    PowerRequired: "Güç Gerekli",
    AchievementVancouver100: "Sap Satıcısı",
    AchievementVancouver100Desc: "Tek Seferde Vancouver'da 100 İsviçre Parası kazanın",
    AchievementVancouver500: "Şurup Savantı",
    AchievementVancouver500Desc: "Tek Seferde Vancouver'da 500 İsviçre Parası kazanın",
    AchievementVancouver1000: "Canuck Fatihi",
    AchievementVancouver1000Desc: "Tek Seferde Vancouver'da 1000 İsviçre Parası kazanın",
    BarbariansAtTheGate: "Kapıdaki Barbarlar",
    BarbariansAtTheGateDesc: "Piyasa güncellemeleri arasında 1 trilyon değerindeki oyuncu ticaret kotasını kullanın",
    DiversifiedProductions: "Çeşitlendirilmiş Prodüksiyonlar",
    DiversifiedProductionsDesc: "Tek bir haritada 100 farklı türde bina inşa edin",
    RealEstateTycoon: "Emlak Kralı",
    RealEstateTycoonDesc: "Tek bir haritada 400 binaya sahip olun",
    ResourceExplorer2DescV2:
        "Kaynak araştırmacıları 2 kat çıktı üretir ancak 2 kat güç kullanır. Tedarik Zinciri Güçlendirici politikası etkinse ve güçlendiricinin aynı çıktıya sahip bitişik bir madeni varsa, kaynak kaşifleri kaynak artırıcılar tarafından güçlendirilebilir",
    NoTileModifier: "Dünya Düzdür",
    NoTileModifierDesc:
        "Tüm döşeme değiştiricileri sıfırdır. Bu politika Doğanın Gücü ve Döşeme Değiştirici Plus politikalarını devre dışı bırakacaktır",
    DoubleTileModifierDescV2:
        "Tüm döşeme değiştiricilerin etkisi x2 - hem olumlu hem de olumsuz. Bu politika Dünya Düzdür politikasını devre dışı bırakacaktır",
    TileModifierOutputOnlyDescV2:
        "Döşeme değiştiricileri hem giriş hem de çıkış yerine yalnızca çıkışı etkiler ancak yalnızca %50 etkilidir. Bu politika Dünya Düzdür politikasını devre dışı bırakacaktır",
    QuickLinks: "Hızlı Linkler",
    GetHelp: "Yardım almak",
    GetHelpBeginnerGuides: "Yeni başlayanların rehberi",
    GetHelpSteamGuides: "Diğer Steam Kılavuzları",
    GetHelpInGameChat: "Oyun İçi Sohbete Sor",
    GetHelpDiscord: "Yardım için Discord Sunucumuza katılın",
    GetHelpWiki: "Topluluk Wikisi",
    SelectATile: "Bir Döşeme Seçin",
    PledgeAmount: "Taahhüt Değeri %{amount}",
    PledgeValue: "Değer $%{amount}",
    TotalPledgedValue: "Toplam Taahhüt Edilen Değer",
    TotalPledgedValueDesc:
        "İlk katkınız kitle fonlaması hedefine yöneliktir. Sonraki katkılar toplam taahhüt edilen değeri artırır ancak hedefe yönelik sayılmaz",
    ReturnOnPledge: "Taahhüt İadesi",
    CrowdfundingEndIn: "Bitiş tarihi %{time}",
    ClaimCrowdfundingReward: "Ödül Talebi %{amount}",
    PledgeSuccessful: "Taahhüt verdin %{amount} bu kitlesel fonlamaya",
    CrowdfundingClaimSuccessful: "Siz Talep Ettiniz %{amount} Nakit",
    CrowdfundingAlreadyPledged: "Zaten Taahhüt Vermiştiniz",
    CrowdfundingAlreadyPledgedDesc:
        "Daha fazla kaynak bağışlayabilirsiniz, bu da toplam taahhüt ettiğiniz değeri artırır (ve potansiyel getiri), ancak kitlesel fonlama hedefine dahil edilmeyecek",
    WholesaleCenterProducingOnly: "Toptan Satış Ortakları",
    WholesaleCenterProducingOnlyDesc:
        "Toptan satış merkezi siparişleri yalnızca şu anda üretilmekte olan kaynakları içerir (ayrıca toptan satış merkezinin kilidini açmak için gerekli sayıda kaynak üretiyor olmanız gerekir)",
    SoftwareCompiler: "Yazılım Derleyicisi",
    SearchEngine: "Arama motoru",
    SearchEngineCompany: "Arama Motoru Şirketi",
    Navy: "Donanma",
    NavyCommand: "Donanma Komutanlığı",
    Battleship: "Savaş Gemisi",
    BattleshipFactory: "Savaş Gemisi Fabrikası",
    ResourceMovementHide: "Her zaman sakla",
    ResourceMovementShow: "Her zaman göster",
    ResourceMovementViewport: "Görünüm Alanında",
    ResourceMovementHighlight: "Vurguda",
    ResourceMovementLine: "Yalnızca Hat",
    ResourceMovement: "Kaynak Hareketi",
    ResourceMovementDesc:
        "Kaynak hareketinin ne zaman gösterileceğini seçebilirsiniz (noktalar). Gizlemek performansı artırabilir",
    CrowdfundingCashInWarning: "Bekleyen kitlesel fonlama taahhütleriniz var - yeni bir şehirde başlarsanız onları kaybedeceksiniz",
    ResourceBoosterBannerDescV2:
        "💡 Şuan  %{number} kadar  kaynak yükselticin var- her birinin bilim girdisi, şu anda sahip olduğunuz kaynak güçlendiricilerin sayısına göre ölçeklendirilir",
    CrowdfundingId: "Kitlesel fonlama %{id}",
    PatchNotes: "Yama Notları",
    PatchNotesDesc: "Bu güncellemedeki yenilikleri okuyun",
    PanelPositionLeft: "Sol (Yerleşik)",
    PanelPositionLeftFloat: "Sol (Kayan)",
    PanelPositionRight: "Sağ (Yerleşik)",
    PanelPositionRightFloat: "Sağ (Kayan)",
    PanelPositionAuto: "Oto",
    TimePlayed: "Oynanan Süre",
    ValuationPerHour: "Saatlik Değerlendirme",
    HighPowerPriority: "Yüksek Güç Önceliği",
    HighPowerPriorityDesc: "Bunu seçeneği açmak binanın diğer binalardan önce güç çekmesini sağlayacaktır",
    IndustryZone: "Sanayi Bölgesi",
    IndustryZoneDesc: "Tedarik zinciri oluşturan bitişik binaları birleştirin ve inşaat izinlerinden tasarruf edin",
    IndustryZoneMaxBuildingLevel: "Maksimum Bina Seviyesi",
    IndustryZoneNotWorkingDesc:
        "Bitişik binaların tümü bir tedarik zinciri oluşturmalı ve diğer sanayi bölgelerinin parçası olmamalıdır.",
    PlayerTradeAutoClaim: "Doldurulan işlemleri otomatik olarak talep edin",
    MusifyInc: "Musify Şirketi",
    WebflixInc: "Webflix Şirketi",
    CloudStreaming: "Bulut Akışı",
    GameCloudInc: "Oyun Bulutu Şirketi",
    SuperComputerLab: "Süper Bilgisayar Laboratuvarı",
    SuperComputer: "Süper Bilgisayar",
    SkyNetInc: "SkyNet Şirketi",
    SkyNet: "SkyNet",
    RobocarFactory: "Robot Araba Fabrikası",
    Robocar: "Robot Araba",
    WarehouseBuildingPermitSave: "Depo İzin Yasası",
    WarehouseBuildingPermitSaveDesc: "Her iki depodan bir tanesi ücretsiz inşaat ruhsatı veriyor",
    PolicySearchPlaceholder: "Aramak için bir politika adı yazın",
    SwissUpgrade: "Swiss Yükseltmesi",
    SwissUpgradeDesc: "Swiss Yükseltmesi kalıcıdır ve yeni bir şehirde başlarsanız devam eder",
    SwissBoost: "Swiss Hızlandırması",
    SwissBoostDesc: "Swiss Hızlandırması yalnızca mevcut oyununuzu etkiler ve yeni bir şehirde başlarsanız sıfırlanır",
    ProductionMultipliers: "Üretim Çarpanları",
    MultiplierMapUniqueBonus: "Haritanın özel bonusu:",
    MultiplierSwissUpgrade: "Swiss Yükseltmesi (Kalıcı)",
    MultiplierSwissBoost: "Swiss Hızlandırması (Geçici)",
    SwissBoostCostDivider: "Swiss Hızlandırması Maliyet Bölücü",
    SwissBoostCostDividerDesc: "Swiss Takviyesi maliyetini bu bölene bölün - yalnızca çarpan/bölen yükseltmeleri için geçerlidir",
    AirForceCommand: "Hava Kuvvetleri Komutanlığı",
    AirForce: "Hava Kuvvetleri",
    StealthFighterFactory: "Gizli Savaşçı Fabrikası",
    StealthFighter: "Gizli Savaşçı",
    ArmyCommand: "Ordu Komutanlığı",
    Army: "Ordu",
    GreenPeacekeeper: "Yeşil Barış Muhafızı",
    GreenPeacekeeperDesc: "Orduyu, donanmayı, hava kuvvetlerini veya uzay kuvvetlerini yalnızca yenilenebilir enerji santralleri (rüzgar/güneş) ile yapın",
    DotComTycoon: "DotCom Kralı",
    DotComTycoonDesc:
        "Aynı harita üzerinde 10. seviye Social Network Şirketi, 10. seviye Arama Motoru Şirketi, 10. seviye SkyNet Şirketi ve 10. seviye Musify Şirketini oluşturun",
    ConstructionNotResearched: "Araştırılmadı",
    OfflineEarningDescV2: "Çevrimdışı kazanç mevcut araştırmanıza, üretiminize ve otomatik satışınıza bağlıdır",
    HighSpeedWarehouse: "Yüksek Hızlı Depo",
    HighSpeedWarehouseDesc:
        "Depolar 2 kat kapasiteye ve %50 daha hızlı iç ve dış taşıma hızına sahiptir, ancak 2 kat daha fazla güç kullanırlar",
    IndustryZoneMultiplierDesc: "Sanayi Bölgesi Bonusu",
    IndustryZoneMultiplierSwissBoost: "Sanayi Bölgesi Kapasite Arttırıcı",
    EarningPerMinuteV2: "Çevrimdışı Kazanç Oranı",
    OfflineResearchPoint: "Çevrimdışı Araştırma Noktası",
    WholesaleCenterOrderFasterV2: "Daha Büyük Daha Hızlı Toptan Satış",
    OfflineResearchSwissBoost: "Çevrimdışı Araştırma",
    OfflineResearchSwissBoostDesc:
        "Araştırma puanları siz çevrimdışıyken oluşturulur (Araştırma Laboratuvarı seviyenize, deponuzdaki Bilime ve çevrimdışı kazanma sürenize göre)",
    SanJose: "San Jose",
    SanJoseBonus:
        "<li>Benzersiz Bina: Çip üreticisi</li><li>Benzersiz Bina: FaceApp Şirketi</li><li>Benzersiz Bina: Bitcoin Madeni</li><li>Silikon tüketen tüm binalarda maksimum döşeme değiştirici bulunur</li><li>Güneş panelleri 2 kat güç üretiyor</li><li>Silikon madenleri 2 kat çıktıya sahiptir</li>",
    RotterdamBonusV2:
        "<li>Çelik Fabrikaları 2 kat kapasiteye sahip</li><li>Paslanmaz Çelik Fabrikaları 2 kat kapasiteye sahip</li><li>Bedava Demir Taşımacılığı</li><li>Çelik taşımanın maliyeti %50 daha az yakıttır</li><li>2 kat otomatik satış kapasitesiyle başlayın</li><li>Dünya Düzdür politikası ücretsizdir</li>",
    ChipManufacturer: "Çip Üreticisi",
    SnapTokInc: "SnapTok Şirketi",
    FaceAppInc: "FaceApp Şirketi",
    BitcoinMiner: "Bitcoin Madeni",
    GalvanicBatteryFactory: "Galvanik Batarya Fabrikası",
    BaseProductionMultiplier: "Temel Üretim",
    ShowBreakdown: "Dökümü Göster",
    HideBreakdown: "Dökümü Gizle",
    IndustryZoneMultiplierSwissBoostDescV2:
        "Bir sanayi bölgesi içindeki üretim zincirinin her kademesi, aynı bölgedeki tüm binalara bu kapasite artışını sağlar",
    IndustryZoneBuildingPermitDesc:
        "Bir sanayi bölgesinin N kademeli üretimleri varsa, ücretsiz olarak N-2 inşaat izni verecektir",
    CrowdfundingBackersReturn: "Destekçiler: %{backers}, Cari Dönüş: %{return}",
    CrowdfundingBackersNeeded: "%{backers} Daha Fazla Destekçi(ler)",
    CrowdfundingReturnBonus: "+%{return} Geri dönmek",
    ReturnOnPledgeDescV2:
        "Toplam getiriniz, toplam taahhüt edilen değerin tüm kaynaklardan elde edilen getiri oranlarıyla çarpımına eşittir. Bir kaynağın daha fazla destekçisi onun getirisini artıracaktır",
    AchievementSanJose100: "Girişim Hobisi",
    AchievementSanJose100Desc: "Tek seferde San Jose'de 100 Swiss Parası kazanın",
    AchievementSanJose500: "Girişim Meraklısı",
    AchievementSanJose500Desc: "Tek seferde San Jose'de 500 Swiss Parası kazanın",
    AchievementSanJose1000: "Risk Kapitalisti",
    AchievementSanJose1000Desc: "Tek seferde San Jose'de 1000 Swiss Parası kazanın",
    AchievementCrowdfundingTycoon: "Kitlesel Fonlama Kralı",
    AchievementCrowdfundingTycoonDesc: "Tek bir kitlesel fonlamada 1Qa değerinde kaynak taahütü verin",
    AchievementCashIsKing: "Nakit Kralı",
    AchievementCashIsKingDesc: "Tek seferde 1 Qa nakit para elinizin altında olsun",
    AchievementPowerTycoon: "Güç Kralı",
    AchievementPowerTycoonDesc: "Tek seferde 1 GW güç üretin",
    PlayerTradeFilteringNResources: "Filtreleme %{n} Kaynak(lar)",
    PlayerTradeFilterResources: "Kaynakları Filtrele",
    PlayerTradeFilterClear: "Filtreleri Temizle",
    ResourceExplorerAll: "Tüm Kaynakları Keşfedin",
    ResourceExplorerAllDesc:
        "Kaynak kaşifleri, haritada bulunmayanlar da dahil olmak üzere tüm kaynakları üretebilir (bu, ilgili teknolojilerin kilidini açmaz)",
    ShowResourceInTopBar: "Üst Çubukta Göster",
    LeaderboardOptOutDescV2:
        "Artık skor tablosunda görünmeyeceksiniz. Bu aynı zamanda oyuncu ticaretini de devre dışı bırakacaktır. LÜTFEN DİKKAT: Skor tablosunu daha sonra etkinleştirmek isterseniz verilerinizin sıfırlanması gerekir",
    PolicyPointNoCopperDesc:
        "💡 Bu haritada bakır yatakları yok, daha fazla teknolojinin kilidini açmak için Alüminyum Devre politikasını etkinleştirebilirsiniz",
    Pumpkin: "Balkabağı",
    PumpkinBattery: "Balkabağı Bataryası",
    PumpkinBatteryDesc: "Batarya tüketen tüm binalar bunun yerine balkabağı kullanıyor (BEDAVA POLİTİKA)",
    PumpkinSteel: "Balkabağı Çeliği",
    PumpkinSteelDesc: "Çelik tüketen tüm binalar bunun yerine balkabağı kullanıyor (BEDAVA POLİTİKA)",
    RequireExpansionPack2: "Genişletme Paketi 2",
    ExpansionPack2: "Genişletme Paketi 2",
    RequireExpansionPack2Desc: "Bu yalnızca şunlar için kullanılabilir: Genişletme Paketi 2",
    Reindeer: "Ren geyiği",
    ReindeerSilicon: "Ren Geyiği Silikonu",
    ReindeerSiliconDesc: "Silikon tüketen tüm binalar bunun yerine ren geyiği kullanıyor (BEDAVA POLİTİKA)",
    ReindeerAluminum: "Ren Geyiği Alüminyum",
    ReindeerAluminumDesc: "Alüminyum tüketen tüm binalar bunun yerine ren geyiği kullanıyor (BEDAVA POLİTİKA)",
    SantaClauseIsComing: "Noel Baba Geliyor",
    SantaClauseIsComingDesc:
        "Noel Baba fabrikaları ren geyiği ve oyuncak tüketiyor ve Noel Baba, bilim ve kültür üretiyor. Noel Baba fabrikalarında maksimum döşeme değiştirici bulunur. Oyuncak fabrikaları oyuncağın yanı sıra ren geyiği de üretiyor (BEDAVA POLİTİKA)",
    MetaRebranding: "Meta Yeniden Markalama",
    MetaRebrandingDesc:
        "Social Network Şirketi, Meta Şirketi olarak yeniden adlandırıldı ve bunun yerine internet, oyun, süper bilgisayar, bitcoin ve dogecoin tüketiyor",
    MetaInc: "Meta Şirketi",
    ImportSave: "Kaydı İçeri Aktar",
    ClearMyTrades: "İşlemlerimi Temizle",
    SaveVersionTooNew:
        "Kaydettiğiniz yer: %{saveVersion} ama senin oyunun %{gameVersion}. Lütfen önce oyununuzu güncelleyin",
    LeaderboardByFlag: "Oyuncu Bayrağına Göre Tablolama",
    LeaderboardByMap: "Haritaya Göre Tablolama",
    LeaderboardByFlagPlayerFlag: "Bayrak",
    LeaderboardByFlagPayerCount: "#",
    LeaderboardByFlagPayerValuationPerHour: "V/H",
    LeaderboardByFlagPayerSwissMoney: "Swiss",
    PlayerTradePriceFilter: "Price Filter",
    PlayerTradeFilterBetterThanMarket: "Better than Market",
    PlayerTradeFilterAll: "Hepsi",
    PlayerTradeFilterBestPrice: "En iyi fiyat",
    CrowdfundingTotalPledgdeValueTooLarge:
        "Kitlesel fonlama için Taahhüt Edilen Toplam Değeriniz mevcut Piyasa Değerinizi aşamaz",
    BuildingSourceAuto: "Otomatik Kaynak",
    BuildingSourceManual: "🔍 Manuel Kaynak",
    BuildingSourceReset: "Sıfırlama",
    BuildingSourceSelecting: "Haritaya dokunun...",
    BuildingSourceSetOverride: "Geçersiz kıl",
    BuildingSourceFallback: "Manuel Kaynak Geri Dönüşü",
    BuildingSourceFallbackDesc:
        "Manuel kaynak yeterli değilse bina girdisini nasıl taşımalıdır? Atla - taşımayın; tahliye - kalanları taşıyın; yeni - yeni bir kaynak bulmak için otomatik kaynağı kullan",
    BuildingSourceFallbackSkip: "Atla",
    BuildingSourceFallbackDrain: "Boşaltmak",
    BuildingSourceFallbackAuto: "Yeni",
    BuildingSourceFallbackMarker: "(Geri çekilmek)",
    BuildingSourceFallbackMarkerDesc: "Manuel kaynakta yeterli kaynak yok, geri dönüş stratejisi etkin",
    BuildingSourceInvalid: "Seçtiğiniz kaynak geçersiz, lütfen geçerli bir kutucuk seçin",
    RandomIsland: "Rastgele Ada",
    RandomIslandBonus:
        "<li>Her başladığınızda harita rastgele seçilir</li><li>Harita boyutu, ızgara türü, kaynak mevduatları ve benzersiz bonusların tümü rastgele alınır</li><li>5 dakikalık bir soğuma süresi vardır; yeniden kayıt yalnızca minimum 5 dakika arayla gerçekleşir</li>",
    RandomIslandBonusDesc: "Rastgele Ada'daki benzersiz bonus, haritaya her başladığınızda yeniden verilir",
    RandomIslandBonusCapacity: "%{building} sahip olmak %{multiplier}x kapasite",
    RandomIslandBonusProductivity: "%{building} sahip olmak %{multiplier}x üretkenlik",
    RandomIslandBonusResources: "Bu haritadaki kaynak yatakları: %{deposits}",
    ValuationPerActiveMinute: "Aktif Dakika Başına Değerleme",
    Perth: "Perth",
    GV: "Jeotermal Havalandırma",
    GeothermalPowerPlant: "Jeotermal Enerji Santrali",
    AdjacentExplorer: "Bitişik Gezgin",
    AdjacentExplorerDesc:
        "Bir kaynak araştırmacısı, ürettiği kaynağa bitişikse 2 kat çıktı üretir (BEDAVA POLİTİKA)",
    FactoryMining: "Fabrika Madenciliği",
    FactoryMiningDesc:
        "Bir fabrika aynı depozitoyu tüketiyorsa depozitoyu doğrudan karodan çıkarabilir (BEDAVA POLİTİKA)",
    FactoryMiningBanner: "Bu bina madencilik amaçlı %{resource} doğrudan bu döşemeden",
    WarehouseSourceWeight: "Ağırlık: %{weight}",
    YAxisStartsFromZero: "Y Axis From 0",
    YAxisStartsFromZeroDesc: "Tüm grafiklerin Y ekseni otomatik olarak ayarlanmak yerine her zaman 0'dan başlayacaktır",
    OwnDLC: "Sahip olmak %{number}x Genleşme(ler)",
    GeneralServerSuccessMessage: "İsteğiniz tamamen başarıyla karşılandı",
    GeneralServerErrorMessage: "Sunucudan gelen hata: %{error}",
    WarehouseInputRoutes: "Giriş Yolları",
    WarehouseOutputRoutes: "Çıkış Yolları",
    InputCapacity: "Üretim Kapasitesi",
    MultipleSources: "Çoklu Kaynaklar",
    MultipleSourcesDesc:
        "Binanın bir üretim döngüsü sırasında birden fazla kaynaktan gelen kaynakları potansiyel olarak taşımasına izin verin",
    Water: "Su",
    KansasCity: "Kansas City",
    Dam: "Hydro Baraj",
    DamDesc: "Hidro baraj bitişikteki boş kiremitleri su kiremitine dönüştürüyor",
    Farmland: "Tarım arazisi",
    FarmlandDesc: "Su karosunun üstünde mahsul üretin",
    Storage: "Depolamak",
    Rice: "Pirinç",
    Corn: "Mısır",
    Wheat: "Buğday",
    Soybean: "Soya Fasulyesi",
    Sugarcane: "Şeker Kamışı",
    Vegetable: "Sebze",
    FarmlandOfflineFarming: "Çevrimdışı Tarım",
    FarmlandOfflineFarmingDesc:
        "Çevrimdışı olduğunuzda doğal su kaynağının üzerine inşa edilen tarım arazileri. Çevrimdışı kazanma süresine tabidir ve Swiss yükseltmelerinden etkilenir",
    FarmlandProductionDesc: "💡 Tarım arazileri her 10 saniyenin yalnızca 5 saniyesinde çalışır; tüm döngüler aynı hizadadır",
    WaterPump: "Su Pompası",
    Greenhouse: "Sera",
    GreenhouseDesc: "İstediğiniz ürünü üretin",
    WaterEntityLevelTooHighDesc:
        "Bina seviyeniz bitişikteki hidro baraj seviyesinden daha yüksek. Lütfen hidro barajınızı yükseltin",
    AirLiquidizer: "Hava Sıvılaştırıcı",
    CapacitorFactory: "Kondansatör Fabrikası",
    Capacitor: "Kondansatör",
    OfflineProduction: "Çevrimdışı Üretim",
    OfflineProductionDesc: "Kapasitörlerin bu binaya taşınması, çevrimdışı olduğunuzda binanın çalışmasına olanak tanıyacak",
    Moderator: "Moderatör",
    FlourMill: "Un değirmeni",
    Flour: "Un",
    FlourMillAdjustMix: "Un Karışımını Ayarlayın",
    RiceFlour: "100% Glütensiz",
    RiceFlourDesc: "Un fabrikaları buğday yerine pirinç tüketiyor",
    Bread: "Ekmek",
    Bakery: "Fırın",
    Fodder: "Yem",
    FodderFactory: "Yem Fabrikası",
    SugarRefinery: "Şeker Rafinerisi",
    RefinedSugar: "Rafine Şeker",
    ShowSupplyChain: "Tedarik Zincirini Göster",
    ShowSupplyChainDesc:
        "Bir binayı vurguladığınızda, yukarı ve aşağı yöndeki tüm binalardan tedarik zincirinin tamamını gösterin",
    Cake: "Kek",
    ChooseARecipe: "Bir Tarif Seçin",
    ChickenFarm: "Tavuk Çiftliği",
    Chicken: "Tavuk",
    Egg: "Yumurta",
    CowFarm: "İnek Çiftliği",
    Beef: "Sığır Eti",
    Milk: "Süt",
    DairyFactory: "Süt Fabrikası",
    Cheese: "Peynir",
    Cookie: "Kurabiye",
    Butter: "Tereyağı",
    UnlockAtLevel: "Seviyede Kilidini Aç %{level}",
    FastFoodChain: "Fast food zinciri",
    Burger: "Hamburger",
    Sandwich: "Sandviç",
    StandbyMode: "Bekleme Modu",
    StandbyModeDesc:
        "Oyunun simülasyonu arka planda çalışmaya devam edecek ancak herhangi bir grafik oluşturmayacak. Bu, GPU kullanımını önemli ölçüde azaltacak ve CPU kullanımını da orta derecede azaltacaktır.",
    StandbyModeOn: "Bekleme Modu Açık",
    StandbyModeOnDesc: "Oyun arka planda çalışıyor. Bekleme modundan çıkmak için herhangi bir yere dokunun",
    PigFarm: "Domuz Çiftliği",
    Pork: "Domuz eti",
    SausageFactory: "Sosis Fabrikası",
    Sausage: "Sosis",
    Hotdog: "Sosisli sandviç",
    BatchOperationDesc: "Bu aşağıdakiler için geçerli olacaktır: %{number} bina(lar). Devam etmek istiyor musun?",
    BatchOperationResult: "Toplu işleminiz şu tarihte tamamlandı: %{success} bina(lar)",
    StreamingMakeMeDiscoverable: "Beni Keşfedilebilir Yap",
    StreamingMakeMeDiscoverableDesc:
        "Diğer oyuncuların oyununuzu izlemesine izin verin. Bağlantı eşler arasıdır ve yalnızca oyununuz yayınlanır. Mikrofona veya web kamerasına erişilmeyecek",
    StreamAutoApprove: "Herkese Açık Yayın",
    StreamAutoApproveDesc: "Bireysel isteği onaylamanızı gerektirerek oyuncuların akışınıza katılmasına olanak tanır",
    StreamingWatch: "İzle",
    StreamingStop: "Dur",
    StreamingPlayerDisconnected: "%{player} akışla bağlantı kesildi",
    StreamingPlayerRejected: "%{player} yayın isteğinizi reddetti",
    StreamingPlayerRequested: "%{player} yayınınızı izleme talebinde bulundu, kabul etmek veya reddetmek için Genel Merkez'e gidin",
    StreamingSettings: "Yayın Ayarları",
    StreamingAvailableStreams: "Mevcut Akışlar",
    StreamingAudience: "İzleyiciler",
    StreamingStopStream: "Bu İzleyici İçin Yayını Durdur",
    StreamingAcceptStream: "Kabul Et",
    StreamingRejectStream: "Reddet",
    StreamingStopStreamDesc: "Bu İzleyici İçin Yayını Durdur",
    StreamingConnectionFailed:
        "Eş bağlantı kurulamadı; büyük olasılıkla ağınız P2P bağlantısını desteklemiyor",
    Pizza: "Pizza",
    StreamingStartRecord: "Kayda başla",
    StreamingRecordCamera: "Bir Yönetmen Kurgusu Kaydet",
    StreamingRecordCameraDesc:
        "10 saniyelik önceden yönlendirilmiş bir sekans kaydedin; kamera maksimum yakınlaştırmaya ayarlanacak ve yavaşça uzaklaştırılacaktır",
    StreamingStopRecord: "Kaydı Durdur",
    StreamingRecordingReady: "Kayıt Hazır",
    StreamingRecordingReadyDesc: "Kayıt dosyanızı kaydedebilir ve uyumlu bir video oynatıcıda oynatabilirsiniz.",
    StreamingRecordingSave: "Farklı kaydet",
    Lantern: "Fener",
    LunarNewYear22: "Kaplan Yılı",
    LunarNewYear22Desc:
        "Kağıt tüketen tüm binalar bunun yerine Fener kullanacak ve 2 kat kapasiteye sahip olacak. Kağıt fabrikaları Kağıt Akademisi oluyor, kültür üretiyor",
    PaperAcademy: "Kağıt Akademisi",
    FriedRice: "Kızarmış pirinç",
    Highlight: "🔍 Vurgulamak",
    BatchMode: "Toplu modu",
    BatchModeAll: "Hepsi",
    BatchModeAdjacent: "Bitişik",
    BatchModeCluster: "Küme",
    BatchUpgradeToLevelX: "Seviye'ye %{level}",
    ApplyToBatch: "Başvurmak %{batch}",
    BatteryRecycler: "Batarya Geri Dönüştürücü",
    BatteryShell: "Batarya Kabuğu",
    StartInANewCity: "Yeni Bir Şehirde Başlayın",
    StartInANewCityFinePrint: "(Veya Bulunduğunuz Şehri Yeniden Başlatın)",
    BatteryFuelDesc:
        "💡 Bataryalar yakıt olarak kullanıldıktan sonra batarya kabuğuna dönüşecekler. Bunları geri dönüştürmek veya yeniden şarj etmek için Batarya Geri Dönüşümcüleri oluşturabilirsiniz",
    FriedChicken: "Kızarmış tavuk",
    Coffee: "Kahve",
    Cocoa: "Kakao",
    CornSyrup: "Sıvı Şeker",
    CornSyrupDesc: "Şeker rafinerileri şeker kamışı yerine mısırla rafine şeker üretiyor",
    Crop: "Mahsul",
    FishPond: "Akvaryum",
    Fish: "Balık",
    LoadGameErrorRetry: "Yeniden dene",
    LoadGameErrorHardReset: "Sert Sıfırlama",
    FontSizeScaling: "Yazı Tipi Boyutu Ölçeklendirme",
    FontSizeScalingDesc: "Kullanıcı arayüzü yazı tipi boyutu ölçeğini değiştirin. Bazı kullanıcı arayüzü öğeleri uygunsuz görünebilir. YENİDEN YÜKLEME GEREKTİRİR",
    FrozenVegetable: "Donmdurulmuş Sebze",
    MilkPowder: "Süt tozu",
    CannedFish: "Konserve balık",
    CocoaPowder: "Kakao tozu",
    FrozenChicken: "Dondurulmuş tavuk",
    FrozenPork: "Dondurulmuş Domuz Eti",
    CannedBeef: "Konserve Sığır Eti",
    FoodProcessingPlant: "Gıda İşleme Tesisi",
    KansasCityBonus:
        "<li>Tarım arazileri ve seralar 2 kat mısır üretiyor</li><li>Ücretsiz mısır taşımacılığı</li><li>Her seviye için hidrobarajlar bitişik tarım arazilerine %5 oranında katkı sağlar</li><li>Her 2 tarım arazisine 1 adet ücretsiz inşaat ruhsatı verilmektedir.</li><li>Güneş Asla Batmaz politikası aynı zamanda tarım arazilerinin her zaman %100 çalışmasını sağlar (çevrimdışı dahil)</li><li>Ürün ticareti yaparken 2 kat oyuncu ticaret kotası</li><li>Gıda işleme tesislerinin kilidi açıldı</li>",
    KansasCityHydroDamBoost: "Kansas City'nin benzersiz bonusu: Bu hidro baraj, bitişikteki tarım arazilerine %{boost} artış sağlıyor",
    PerthGeothermalPowerPlantBoost:
        "Perth'in benzersiz bonusu: Bu jeotermal enerji santrali, çelik üreten bitişik binalara %{boost} artış sağlıyor",
    PerthBonus:
        "<li>Bina çarkları diğer şehirlerin tersine saat yönünde dönüyor</li><li>Benzersiz mevduat: Jeotermal havalandırma</li><li>Benzersiz bina: Jeotermal Enerji Santrali</li><li>Benzersiz politikalar: Bitişik Gezgin (BEDAVA), Fabrika Madenciliği (BEDAVA)</li>",
    Biofuel: "Bio Yakıt",
    RioDeJaneiro: "Rio de Janeiro",
    RioDeJaneiroBonus:
        "<li>Benzersiz yakıt: Biyoyakıt</li><li>Domuz, inek ve tavuk çiftlikleri ekstra biyoyakıt üretiyor</li><li>Benzersiz bina: Biyoyakıt Enerji Santrali</li><li>Benzersiz bina: Cristo Redentor</li><li>Kaynak artırıcılar domuz, inek ve tavuk çiftliklerini güçlendirebilir</li><li>Tomruk kampları 2 kat odun üretiyor</li><li>Kereste fabrikaları 2 kat kapasiteye sahiptir</li><li>Dondurulmuş tavuk, dondurulmuş domuz eti ve konserve sığır etinin 2 katı ticaret kotası vardır</li>",
    BiofuelPowerPlant: "Biofuel Power Plant",
    CristoRedentor: "Cristo Redentor",
    CristoRedentorBanner:
        "Cristo Redentor, daha düşük veya eşit seviyeye sahip tüm binalara bitişik bonus sağlar. Daha fazlasını inşa ederseniz kültür tüketimi katlanarak artar",
    CristoRedentorDesc: "Kültür tüketir ve herhangi bir binaya bitişik bonus sağlar",
    Istanbul: "Istanbul",
    Wormhole: "Solucan deliği",
    WavesSurvived: "Dalgalar Hayatta Kaldı",
    NumberOfWormholes: "Haritadaki Solucan Deliği Sayısı",
    NextWave: "Sonraki Dalga",
    NextWaveUnitHP: "Birim Sağlığı",
    NextWaveTotalCount: "Tüm birimler",
    NextWaveTotalCountDesc: "Her solucan deliğinden doğacak toplam birim sayısı",
    NextWaveSpeed: "Hareket hızı",
    NextWaveSpawnDelay: "Ortaya Çıkma Sıklığı",
    NextWaveSpawnDelayValue: "Her %{number}s",
    NextWaveBonusMultiplier: "Bonus Çarpanı",
    NextWaveBonusMultiplierValue: "%{number}x",
    NextWaveTotalDamageNeeded: "Gereken Toplam Hasar",
    NextWaveTotalReward: "Toplam Ödül",
    StartWave: "Dalgayı Başlat",
    WaveSpawned: "Doğan",
    WaveEliminated: "Elenen",
    WaveFailed: "Kaybeden",
    WaveRetry: "Yeniden dene",
    WaveForfeit: "Cezalı",
    Damage: "Hasar",
    DefenseCommandConvert: "Dönüştürmek",
    DefenseModule: "Savunma Modülü",
    DefenseModuleAddOne: "Savunma Modülü Ekle",
    DefenseModuleRange: "Menzil",
    DefenseModuleDamage: "Hasar",
    DefenseModuleBulletSpeed: "Mermi Hızı",
    DefenseModuleAttackSpeed: "Saldırı Hızı",
    DefenseModuleUpgrade: "Yükseltme",
    DefenseModuleMaxUpgrade: "Maksimum Yükseltme",
    DefenseModuleCriticalDamageChance: "Kritik Hasar Şansı",
    DefenseModuleCriticalDamageChanceShort: "Kritik Hasar %",
    DefenseModuleCriticalDamageMultiplier: "Kritik Hasar Çarpanı",
    DefenseModuleCriticalDamageMultiplierShort: "Kritik Hasar x",
    DefenseModuleBaseModule: "Temel Modül",
    DefenseCommand: "Savunma Komutanlığı",
    DefenseCommandDesc: "Silahlardan hasar üretin ve üssünüzü işgalcilere karşı savunun",
    PathBlocked:
        "Solucan deliklerinden karargâhınıza giden tüm olası yolları kapatacağı için bu döşemenin üzerine inşaat yapamazsınız.",
    WaveInProgressBuildRemoveDisabled:
        "İstila dalgası devam ederken yol üzerine bina inşa edemez veya binaları satamazsınız.",
    ExportSaveForTransfer: "Kaydınızı Aktarın",
    ExportSaveForTransferDesc:
        "Kayıtlarınızı cihazlar arasında aktarmak istiyorsanız bu seçeneği seçin. Bu işlem yapma hakkınızı kaydetme dosyanıza aktaracaktır; kaydetme dosyasını içe aktardıktan sonra ticarete devam edebilirsiniz. Mevcut cihazınız bekleme süresini beklemeden işlem yapamayacak",
    ExportSaveForBackup: "Kayıtlarınızı Yedekleyin",
    ExportSaveForBackupDesc:
        "İlerlemenizin yedeğini almak istiyorsanız bunu seçin. Bu, mevcut cihazınızda işlem yapma hakkınızı bırakacaktır - yedek kaydetme dosyasını içe aktarmak, bir bekleme süresi beklemeden işlem yapma hakkını geri yüklemeyecektir.",
    RightToTradeValid: "Ticaret Hakkı",
    RightToTradeInvalid: "Ticaret Hakkı Yok",
    RightToTradeInvalidDesc:
        "Bunun nedeni, ticaret hakkınızın başka bir kayıt dosyasına aktarılmış olmasıdır; ticaret hakkınızı geri yüklemek için bu kayıt dosyasını içe aktarmalısınız. Bu kayıt dosyasını kaybettiyseniz, bu kayıtta takas hakkınızı geri almaya zorlayabilirsiniz ancak bir bekleme süresine tabi olursunuz ve diğer tasarrufunuz takas hakkını kaybeder",
    ForceRestoreRightToTrade: "Geri Yüklemeyi Zorla (%{cooldown}-saat bekleme süresi)",
    ImportSaveRestoreFail: "Sunucuya bağlanılamadı, lütfen internet bağlantınızı kontrol edin",
    DefenseCommandConvertDesc: "Mevcut ticaret merkezi fiyatı üzerinden kaynakları hasara dönüştürün",
    MousewheelSensitivity: "Fare Tekerleği Yakınlaştırma Hassasiyeti",
    MousewheelSensitivityDesc: "Yakınlaştırmak/uzaklaştırmak için fare tekerleğini kaydırırken hassasiyeti ayarlayın",
    PlayerTradeFilterWhatIHave: "Sahip Olduğum Şeyleri Filtrele",
    PathTemporarilyBlocked:
        "Devam eden bir dalga olduğundan bu döşemenin üzerine inşaat yapamazsınız. Dalga bittikten sonra tekrar kontrol edin",
    MoveBuilding: "Binayı Taşı",
    MoveBuildingInvalidTarget: "Bina taşınamadı; hedef kutucuğu geçerli değil",
    MoveBuildingMoving: "Boş Bir Döşeme Seçin...",
    WaveAutoNext: "Otomatik başlatma",
    WaveAutoNextDesc: "Bir dalgayı başarıyla savunduktan sonra otomatik olarak ödülü alın ve bir sonrakine başlayın",
    IstanbulBonus:
        "<li>Tkule savunma modu - silahlarınızı hasara dönüştürün, işgalcilere karşı savunun ve daha fazla genişleme için nakit ödüller kazanın</li><li>Ordu komutanlıkları 2 kat kapasiteye sahip</li><li>Tank fabrikaları 2 kat kapasiteye sahip</li><li>Silah fabrikaları 2 kat kapasiteye sahip</li><li>Füze fabrikaları 2 kat kapasiteye sahip</li><li>Dinamit fabrikaları 2 kat üretkenliğe sahiptir</li>",
    PlayerTradeCancelTitle: "Bu Ticareti İptal Et?",
    PlayerTradeCancelDescV2: "The tariff paid on this trade will NOT be refunded",
    PlayerTradeCancelYes: "İşlemi İptal Et",
    PlayerTradeCancelNo: "İptal Etmeyin",
    SteamAutoCloudBackupDescV3:
        "En son ilerlemeniz Steam Cloud'a kaydedilir. Oyun ayrıca her 10 dakikada bir yedeklenir; istediğiniz zaman yedeklemeyi zorlayabilirsiniz. Yedeklemenin yüklenmesi, takas hakkını kaybeder ve gücün geri yüklenmesini gerektirir (bekleme süresine tabidir)",
    BuyFromTradeCenter: "Ticaret Merkezinden Satın Alın",
    BuyFromTradeCenterBestBid: "Oyuncu takaslarından en iyi teklif fiyatı",
    BuyFromTradeCenterBestAsk: "Oyuncu takaslarından en iyi fiyat teklifi",
    BuyFromTradeCenterAveragePrice: "Ortalama %{price}",
    PlayerTradesAvailable: "%{number} ticaret(ler) oyunculardan temin edilebilir",
    SettingsShowInToolbar: "Araç Çubuğunda Göster",
    AccountVerification: "Doğrulama",
    AccountAuthenticated: "Kimliği doğrulandı",
    AccountNotAuthenticated: "Kimliği doğrulanmadı",
    AccountTrusted: "Güvenilir Hesap",
    AccountLimited: "Sınırlı Hesap",
    AntiCheatPass: "Hile Önleme Kartı",
    AntiCheatFail: "Hile Karşıtı Başarısızlık",
    AchievementIstanbul100: "Büyük Aslan",
    AchievementIstanbul100Desc: "Tek Seferde İstanbul'da 100 Swiss Parası Kazanın",
    AchievementIstanbul500: "Büyük Jüstinyen",
    AchievementIstanbul500Desc: "Tek Seferde İstanbul'da 500 Swiss Parası Kazanın",
    AchievementIstanbul1000: "Büyük Konstantin",
    AchievementIstanbul1000Desc: "Tek Seferde İstanbul'da 1000 Swiss Parası Kazanın",
    AchievementPerth100: "Pademelon",
    AchievementPerth100Desc: "Tek Seferde Perth'de 100 Swiss Parası Kazanın",
    AchievementPerth500: "Valabi",
    AchievementPerth500Desc: "Tek Seferde Perth'de 500 Swiss Parası Kazanın",
    AchievementPerth1000: "Kanguru",
    AchievementPerth1000Desc: "Tek Seferde Perth'de 1000 Swiss Parası Kazanın",
    AchievementKansasCity100: "Koçandaki Mısır",
    AchievementKansasCity100Desc: "Tek Seferde Kansas'ta 100 Swiss Parası Kazanın",
    AchievementKansasCity500: "Mısır Köpeği",
    AchievementKansasCity500Desc: "Tek Seferde Kansas'ta 500 Swiss Parası Kazanın",
    AchievementKansasCity1000: "Patlamış mısır",
    AchievementKansasCity1000Desc: "Tek Seferde Kansas'ta 1000 Swiss Parası Kazanın",
    AchievementRioDeJaneiro100: "Leblon",
    AchievementRioDeJaneiro100Desc: "Tek Seferde Rio de Janeiro'da 100 Swiss Parası kazanın",
    AchievementRioDeJaneiro500: "Barra da Tijuca",
    AchievementRioDeJaneiro500Desc: "Tek Seferde Rio de Janeiro'da 500 Swiss Parası kazanın",
    AchievementRioDeJaneiro1000: "Copacabana",
    AchievementRioDeJaneiro1000Desc: "Tek Seferde Rio de Janeiro'da 1000 Swiss Parası kazanın",
    AchievementRandomIsland100: "Bernoulli",
    AchievementRandomIsland100Desc: "Tek Seferde Rastgele Ada'da 100 Swiss Parası kazanın",
    AchievementRandomIsland500: "Poisson",
    AchievementRandomIsland500Desc: "Tek Seferde Rastgele Ada'da 500 Swiss Parası kazanın",
    AchievementRandomIsland1000: "Gauss",
    AchievementRandomIsland1000Desc: "Tek Seferde Rastgele Ada'da 1000 Swiss Parası kazanın",
    AchievementFishPond200: "Balık Göleti Amirali",
    AchievementFishPond200Desc: "Tek seferde herhangi bir haritada 200 balık havuzu inşa edin",
    Photogram: "Fotogram",
    FineDiningRestaurant: "Kaliteli Yemek Restoranı",
    Sushi: "Suşi",
    Pastry: "Hamur işi",
    HappyMeal: "Mutlu yemek",
    Whopper: "Whopper",
    DrinkFactory: "İçecek Fabrikası",
    SoftDrink: "Meşrubat",
    Alcohol: "Alkol",
    Wine: "Şarap",
    Cocktail: "Kokteyl",
    ThreeCourseMeal: "Üç Çeşit Yemek",
    SixCourseMeal: "Altı Çeşit Yemek",
    NineCourseMeal: "Dokuz Çeşit Yemek",
    IndustryZoneCapacityBoostPermanent: "Sanayi Bölgesi Bonusu (Kalıcı)",
    IndustryZoneCapacityBoostThisRun: "Sanayi Bölgesi Bonusu (Geçici))",
    IndustryZoneMaxBuildingLevelDesc: "Bu Sanayi Bölgesinde desteklenen maksimum bina seviyesi",
    IndustryZoneHelp: "Sanayi Bölgesi Nasıl Çalışır??",
    IndustryZoneProductivityBoost: "Sanayi Bölgesi Plus",
    ExtraBuildingPermit: "Ekstra İnşaat İzni",
    ExtraBuildingPermitDesc: "Mevcut haritanıza ekstra inşaat izinleri ekleyin; bu, maliyet eğrisini artırmaz",
    PanelPositionDescV2:
        "Yan paneli solda, sağda veya otomatik olarak göster (mevcut seçili döşemeye bağlıdır). Yalnızca yatay modda çalışın",
    PanelHeight: "Panel Yüksekliği",
    PanelHeightDesc: "Panelin yüksekliğini seçin. Mobil cihazlarda yalnızca portre modunda çalışın. YENİDEN YÜKLEME GEREKTİRİR",
    AllowPortraitMode: "Portre Modunu Etkinleştir",
    AllowPortraitModeDesc:
        "Bu, portre modunu etkinleştirecek (deneysel), telefonunuzun sensörüne ve ayarlarına göre ekran dönecek",
    IndustryZoneProductivityBoostDesc:
        "Bir Endüstri Bölgesinin her kademesi veya her 10 seviyesi, içindeki binalara %10 üretim artışı sağlar",
    Auckland: "Auckland",
    AucklandBonus:
        "<li>Tüm yataklar haritanın merkezinde Yeni Zelanda şeklindeki bir alanda bulunur</li><li>Benzersiz Bina: Hidroelektrik Santrali</li><li>Benzersiz Politika: Maden Hızlandırıcı</li><li>Benzersiz Politika: Elektrikli Balık Havuzu</li><li>Balık havuzları herhangi bir fayans üzerine inşa edilebilir</li>",
    MineBooster: "Maden Hızlandırıcı",
    MineBoosterDesc:
        "Çalışan bir maden, rezervi tüketen bitişik madenlere veya fabrikalara %100 kapasite artışı sağlar",
    HydroPowerPlant: "Hidroelektrik Santrali",
    ElectricFishPond: "Elektrikli Balık Havuzu",
    ElectricFishPondDesc: "Çalışan her hidroelektrik santral, haritadaki tüm balık havuzlarına %20 kapasite artışı sağlar",
    AccountLimitedDescV2: "Hesabınız platform gereksinimini karşılayamıyor",
    AccountLimitedActionV2: "Sınırlı Hesapla İlgili SSS'yi okuyun",
    CropOutputx2: "Modern Gübre",
    CropOutputx2Desc: "Tarım arazileri ve seralar 2 kat fazla ürün üretiyor ancak mahsul taşıma maliyeti 2 kat yakıt",
    MeatProductionx2: "Hayvancılık Steroidi",
    MeatProductionx2Desc:
        "Tavuk çiftlikleri, domuz çiftlikleri, inek çiftlikleri, balık havuzları ve yem fabrikaları 2 kat kapasiteye sahiptir ancak 2 kat güç kullanır",
    HydroFarming: "Hidro Tarım",
    HydroFarmingDesc: "Çalışan her hidro baraj, haritadaki tüm tarım arazileri ve seralara %20 kapasite artışı sağlar",
    ExtraTradeQuota: "Ekstra Oyuncu Ticareti Kotası",
    ExtraTradeQuotaDesc: "İlk oyuncu takas kotası piyasa değerinizin %1'idir - bu ekstra yüzde verecektir",
    ProduceAllCrops: "Tüm Mahsulleri Üret",
    ProduceAllCropsDesc: "Tarım arazileri ve seralar, haritada bulunmayanlar da dahil olmak üzere tüm mahsulleri üretebilir",
    ResearchAgreement: "Araştırma Anlaşması",
    ResearchAgreementDesc: "Her takası benzersiz bir oyuncuyla doldurmak 10 dakikalık araştırma puanı üretimi sağlar",
    NewsEffectx2V2: "Basın toplantısı",
    NewsEffectx2DescV2: "Tüm piyasa haberleri %50 daha etkili",
    AutoSellCapacityMultiplierV2: "Ekstra Otomatik Satış Kapasitesi",
    AutoSellCapacityMultiplierDescV2: "Bu, mevcut kapasitenize ek olarak ekstra otomatik satış kapasitesi sağlayacaktır",
    AutoSellCapacity: "Otomatik Satış Kapasitesi",
    AutoSellCapacityDescV2:
        "Max amount of resources auto sell can handle per second, per resource, measured as the percentage of your total production of that resource",
    AutoSellCapacityExtraPercentageFromSwiss: "Swiss Yükseltmesi ve Hızlandırmasından Ekstra Yüzde: %{n}%",
    BaselineAutoSellCapacity: "Temel otomatik satış kapasitesi: %{amount}",
    AchievementAuckland100: "Hoiho",
    AchievementAuckland100Desc: "Tek Seferde Auckland'da 100 Swiss Parası Kazanın",
    AchievementAuckland500: "Whio",
    AchievementAuckland500Desc: "Tek Seferde Auckland'da 500 Swiss Parası Kazanın",
    AchievementAuckland1000: "Kiwi",
    AchievementAuckland1000Desc: "Tek Seferde Auckland'da 1000 Swiss Parası Kazanın",
    ExternalManageYourSave: "Kaydınızı İçe ve Dışa Aktarın",
    ExternalManageYourSaveDesc:
        "Teknik sınırlama nedeniyle, kaydetmenizin içe ve dışa aktarımı oyunun resmi web sitesinden yapılmalıdır.",
    MREPlant: "Yemek, Tüketime Hazır Bitki",
    PlayerTradeTaxCreditProduction: "Vergi Kredisi: Üretim",
    PlayerTradeTaxCreditProductionDescV2:
        "Bu vergi kredisi, son piyasa güncellemesinden bu yana ürettiğiniz %{res} miktarına dayanmaktadır. %{produced} ürettiniz ve işlem yaptınız %{used}",
    PlayerTradeTaxCreditMarketCap: "Vergi Kredisi: Piyasa Değeri",
    PlayerTradeTaxCreditMarketCapDesc:
        "Bu vergi kredisi, piyasa değerinizin %{percentage} kadarıdır ve İsviçre Yükseltme/Boost yoluyla yükseltilebilir. Toplam kredi tutarı %{total} ve %{used} kredisini kullandınız",
    PlayerTradeGrossTradeValue: "Brüt Ticaret Değeri",
    PlayerTradeTaxableValue: "Vergiye Tabi Değer",
    PlayerTradeTaxRate: "Vergi oranı",
    PlayerTradeTaxRateDesc:
        "Vergi oranı, yerel fiyatınız ile bu ticaret arasındaki fiyat farkına dayanır; vergi oranı artan oranlıdır. %0 ~ %50: her %1 fark için %0,5; %50 ~ %75: Her %1 fark için %1; %75 ~ %100: Her %1 fark için %2",
    PlayerTradeTaxPayable: "Ödenecek Vergi",
    PlayerTradeTradeValueAfterTax: "Vergi Sonrası Ticari Değer",
    PlayerTradeShowTaxCalculation: "Vergi Hesaplamasını Göster",
    PlayerTradeHideTaxCalculation: "Vergi Hesaplamasını Gizle",
    PlayerTradeMaxTaxCreditValue: "Tutarı Vergi Kredisiyle Eşleşecek Şekilde Ayarlayın",
    WaterProductionx2: "Süper Su Pompası",
    WaterProductionx2Desc: "Su pompaları 2 kat çıkış üretir ancak 2 kat güç tüketir",
    InputBufferTypeAuto: "Otomatik",
    InputBufferTypeStockpile: "Stok",
    InputBuffer: "Kaynak Giriş Arabelleği",
    InputBufferDesc:
        "Bu binadan önce depoda tutulacak maksimum girdi kaynağı döngüsü artık o kaynağı taşımayacaktır. Otomatik, sürekli üretime izin veren minimum tamponu korumak için tahminin kullanılması anlamına gelir. Stok, depolamadaki miktarına bakılmaksızın girdi kaynaklarının her zaman taşınması anlamına gelir",
    InputCapacityOverride: "Giriş Kapasitesini Geçersiz Kılma",
    InputCapacityOverrideDesc: "Her üretim döngüsünde, üretim için gereken kaynakların %{percent} kadarını taşıyın",
    PumpkinSpiceLatte: "Balkabağı soslu latte",
    PumpkinPie: "Balkabağı pastası",
    QuantumComputerLab: "Kuantum Bilgisayar Laboratuvarı",
    QuantumComputer: "Kuantum Bilgisayarı",
    TVStudioPlus: "Televizyon stüdyosu+",
};
